In [3]:
import sqlite3
import pandas as pd
import os

In [4]:
# Path to the database
# Note: Corrected 'claimslens' to 'claimlens' based on directory structure
db_path = '../data_store/claimlens/congress.db'

if os.path.exists(db_path):
    print(f"Connecting to database at: {db_path}")
    try:
        # Connect to the database
        conn = sqlite3.connect(db_path)
        
        # Get all table names
        query = "SELECT name FROM sqlite_master WHERE type='table';"
        tables = pd.read_sql_query(query, conn)['name'].tolist()
        
        print(f"Found {len(tables)} tables: {tables}")
        
        # Display overview for each table
        for table in tables:
            print(f"\n{'='*40}")
            print(f"Table: {table}")
            print(f"{'='*40}")
            
            # Get row count
            count = pd.read_sql_query(f"SELECT COUNT(*) as count FROM {table}", conn).iloc[0]['count']
            print(f"Total rows: {count}")
            
            # Show first 5 rows
            print("First 5 rows:")
            df = pd.read_sql_query(f"SELECT * FROM {table} LIMIT 5", conn)
            display(df)
            
            # Show schema
            print("Schema:")
            schema = pd.read_sql_query(f"PRAGMA table_info({table})", conn)
            display(schema)

    except Exception as e:
        print(f"An error occurred: {e}")
    finally:
        if 'conn' in locals():
            conn.close()
else:
    print(f"Database file not found at {db_path}")
    print(f"Current working directory: {os.getcwd()}")

Connecting to database at: ../data_store/claimlens/congress.db
Found 6 tables: ['Congress', 'Bills', 'sqlite_sequence', 'Members', 'CongressMembers', 'Rollcalls']

========================================
Table: Congress
========================================
Total rows: 44
First 5 rows:

   CongressNumber
0              75
1              76
2              77
3              78
4              79

Schema:

   cid            name     type  notnull dflt_value  pk
0    0  CongressNumber  INTEGER        1       None   1

========================================
Table: Bills
========================================
Total rows: 342466
First 5 rows:

,BillID,BillCongress,BillType,BillNumber,BillDescription,BillSummary,BillSubjects
0,1,111,SCONRES,9,None,Expresses support for the goals and ideals of ...,"Commemorative events and holidays, Congression..."
1,2,111,SCONRES,53,None,"Recognizes the City of Colorado Springs, Color...","Colorado, Congressional tributes, Emergency me..."
2,3,111,SCONRES,64,None,Honors the 28th Infantry Division of the U.S. ...,"Armed forces and national security, Congressio..."
3,4,111,SCONRES,50,None,Recognizes the historic founding of the Black ...,"Civil rights and liberties, minority issues, C..."
4,5,111,SCONRES,52,None,"Expresses support for the goals and ideals of,...","Commemorative events and holidays, Health, Hea..."

Schema:

   cid             name     type  notnull dflt_value  pk
0    0           BillID  INTEGER        0       None   1
1    1     BillCongress  INTEGER        0       None   0
2    2         BillType     TEXT        0       None   0
3    3       BillNumber  INTEGER        0       None   0
4    4  BillDescription     TEXT        0       None   0
5    5      BillSummary     TEXT        0       None   0
6    6     BillSubjects     TEXT        0       None   0

========================================
Table: sqlite_sequence
========================================
Total rows: 1
First 5 rows:

    name     seq
0  Bills  342466

Schema:

   cid  name type  notnull dflt_value  pk
0    0  name             0       None   0
1    1   seq             0       None   0

========================================
Table: Members
========================================
Total rows: 12677
First 5 rows:

  BioguideID                  Name            Wiki
0    B000944         Sherrod Brown   Sherrod Brown
1    C000127        Maria Cantwell  Maria Cantwell
2    C000141    Benjamin L. Cardin      Ben Cardin
3    C000174      Thomas R. Carper      Tom Carper
4    C001070  Robert P. Casey, Jr.   Bob Casey Jr.

Schema:

   cid        name  type  notnull dflt_value  pk
0    0  BioguideID  TEXT        1       None   1
1    1        Name  TEXT        0       None   0
2    2        Wiki  TEXT        0       None   0

========================================
Table: CongressMembers
========================================
Total rows: 12677
First 5 rows:

   CongressNumber BioguideID
0             103    B000944
1             103    C000127
2             100    C000141
3              98    C000174
4             110    C001070

Schema:

   cid            name     type  notnull dflt_value  pk
0    0  CongressNumber  INTEGER        0       None   1
1    1      BioguideID     TEXT        0       None   2

========================================
Table: Rollcalls
========================================
Total rows: 7195798
First 5 rows:

       RollcallID MemberID VoteType  BillID
0  2009-111-h-173  A000358      Nay   12706
1  2009-111-h-173  B000208      Nay   12706
2  2009-111-h-173  B001262      Nay   12706
3  2009-111-h-173  C001075      Nay   12706
4  2009-111-h-173  C001076      Nay   12706

Schema:

   cid        name     type  notnull dflt_value  pk
0    0  RollcallID     TEXT        1       None   1
1    1    MemberID     TEXT        0       None   2
2    2    VoteType     TEXT        0       None   0
3    3      BillID  INTEGER        0       None   3

In [5]:
# Inspect Bills table specifically to match ID format '117 HR 3684'
db_path = '../data_store/claimlens/congress.db'
conn = sqlite3.connect(db_path)

print("Bills Table Schema:")
schema = pd.read_sql_query("PRAGMA table_info(Bills)", conn)
display(schema)

print("\nSample Bills:")
# Select a few columns that might be relevant for ID construction and text content
# Guessing column names based on typical schemas, but relying on SELECT * LIMIT 5 from previous step would be better if I had paid closer attention.
# Let's just get * for a few rows to be sure.
df_bills_sample = pd.read_sql_query("SELECT * FROM Bills LIMIT 5", conn)
display(df_bills_sample)

conn.close()

Bills Table Schema:

   cid             name     type  notnull dflt_value  pk
0    0           BillID  INTEGER        0       None   1
1    1     BillCongress  INTEGER        0       None   0
2    2         BillType     TEXT        0       None   0
3    3       BillNumber  INTEGER        0       None   0
4    4  BillDescription     TEXT        0       None   0
5    5      BillSummary     TEXT        0       None   0
6    6     BillSubjects     TEXT        0       None   0

Sample Bills:

,BillID,BillCongress,BillType,BillNumber,BillDescription,BillSummary,BillSubjects
0,1,111,SCONRES,9,None,Expresses support for the goals and ideals of ...,"Commemorative events and holidays, Congression..."
1,2,111,SCONRES,53,None,"Recognizes the City of Colorado Springs, Color...","Colorado, Congressional tributes, Emergency me..."
2,3,111,SCONRES,64,None,Honors the 28th Infantry Division of the U.S. ...,"Armed forces and national security, Congressio..."
3,4,111,SCONRES,50,None,Recognizes the historic founding of the Black ...,"Civil rights and liberties, minority issues, C..."
4,5,111,SCONRES,52,None,"Expresses support for the goals and ideals of,...","Commemorative events and holidays, Health, Hea..."

In [10]:
import sqlite3
import pandas as pd
import os
import ast
from sentence_transformers import SentenceTransformer, util
import torch
from tqdm import tqdm

# 1. Load Bills from Database
def load_bills(db_path):
    print(f"Loading bills from {db_path}...")
    conn = sqlite3.connect(db_path)
    
    # Select relevant columns
    # Constructing ID as: "{BillCongress} {BillType} {BillNumber}"
    query = """
    SELECT 
        BillCongress, 
        BillType, 
        BillNumber, 
        BillDescription, 
        BillSummary, 
        BillSubjects 
    FROM Bills
    """
    
    df = pd.read_sql_query(query, conn)
    conn.close()
    
    print(f"Loaded {len(df)} bills.")
    
    # Construct ID and Text
    # Text = Title/Description + Summary + Subjects
    
    ids = []
    texts = []
    
    for idx, row in tqdm(df.iterrows(), total=len(df), desc="Processing Bills"):
        # ID Construction
        # Ensure integers are formatted as integers
        try:
            congress = int(row['BillCongress'])
            number = int(row['BillNumber'])
            bill_type = row['BillType']
            bill_id = f"{congress} {bill_type} {number}"
        except ValueError:
            # Fallback if conversion fails
            bill_id = f"{row['BillCongress']} {row['BillType']} {row['BillNumber']}"
            
        ids.append(bill_id)
        
        # Text Construction
        text_parts = []
        if row['BillDescription']:
            text_parts.append(str(row['BillDescription']))
        if row['BillSummary']:
            text_parts.append(str(row['BillSummary']))
        if row['BillSubjects']:
            text_parts.append(str(row['BillSubjects']))
            
        full_text = " ".join(text_parts)
        texts.append(full_text)
        
    return ids, texts

# 2. Load Claims from CSV
def load_claims(csv_path):
    print(f"Loading claims from {csv_path}...")
    df = pd.read_csv(csv_path)
    
    claims = []
    ground_truth = [] # List of sets of bill IDs
    
    for idx, row in df.iterrows():
        claim_text = row['claim_entered']
        sourced_bills_raw = row['sourced_bills']
        
        try:
            # Parse the list string "['ID1', 'ID2']"
            if isinstance(sourced_bills_raw, str):
                bill_ids = ast.literal_eval(sourced_bills_raw)
            else:
                bill_ids = []
                
            if claim_text and bill_ids:
                claims.append(claim_text)
                ground_truth.append(set(bill_ids))
                
        except Exception as e:
            print(f"Error parsing row {idx}: {e}")
            
    print(f"Loaded {len(claims)} valid claims.")
    return claims, ground_truth

# Paths
db_path = '../data_store/claimlens/congress.db'
claims_path = '../data_store/claimlens/vote-claims.csv'

# Load Data
bill_ids, bill_texts = load_bills(db_path)
claims, ground_truth = load_claims(claims_path)

# Create a mapping for quick lookup if needed, though for search we just need the lists
# We need to ensure bill_ids align with bill_texts for the corpus
print(f"First 3 Bill IDs: {bill_ids[:3]}")
print(f"First 3 Bill Texts: {bill_texts[:3]}")

Loading bills from ../data_store/claimlens/congress.db...
Loaded 342466 bills.

Processing Bills: 100%|██████████| 342466/342466 [00:06<00:00, 49887.06it/s]

Loading claims from ../data_store/claimlens/vote-claims.csv...
Loaded 79 valid claims.
First 3 Bill IDs: ['111 SCONRES 9', '111 SCONRES 53', '111 SCONRES 64']
First 3 Bill Texts: ["Expresses support for the goals and ideals of Multiple Sclerosis Awareness Week. Commends the efforts of states, U.S. territories and possessions, and local communities that support such goals and ideals.Reaffirms the U.S. people's commitment to combating multiple sclerosis by promoting awareness about its causes and risks, promoting new education programs, supporting research, and expanding access to medical treatment.Recognizes people living with multiple sclerosis and salutes the health care professionals and medical researchers who assist those living with multiple sclerosisand continue to work to find cures and improve treatments. Commemorative events and holidays, Congressional tributes, Health, Health personnel, Health promotion and preventive care, Medical research, Neurological disorders", 'Recognizes the City of Colorado Springs, Colorado, as the new official site of the National Emergency Medical Services Memorial Service and the National Emergency Medical Services Memorial. Colorado, Congressional tributes, Emergency medical services and trauma care, Health, Health personnel, Monuments and memorials', 'Honors the 28th Infantry Division of the U.S. Army (part of the Pennsylvania Army National Guard) for serving and protecting the United States. Armed forces and national security, Congressional tributes, National Guard and reserves, Pennsylvania']

In [11]:
def evaluate_model(model_name_or_path, corpus_texts, corpus_ids, query_texts, ground_truth, k_values=[1, 5, 10, 50]):
    print(f"Evaluating model: {model_name_or_path}")
    
    # Load model
    try:
        model = SentenceTransformer(model_name_or_path, trust_remote_code=True)
    except Exception as e:
        print(f"Failed to load model {model_name_or_path}: {e}")
        return None

    # Encode Corpus
    print("Encoding corpus...")
    # Using a smaller batch size to be safe with memory, though 32 is usually fine
    corpus_embeddings = model.encode(corpus_texts, batch_size=32, show_progress_bar=True, convert_to_tensor=True)
    
    # Encode Queries
    print("Encoding queries...")
    query_embeddings = model.encode(query_texts, batch_size=32, show_progress_bar=True, convert_to_tensor=True)
    
    # Search
    print("Searching...")
    # We want top K results
    max_k = max(k_values)
    results = util.semantic_search(query_embeddings, corpus_embeddings, top_k=max_k)
    
    # Calculate Metrics
    metrics = {f"Recall@{k}": 0.0 for k in k_values}
    
    for query_idx, hits in enumerate(results):
        gold_ids = ground_truth[query_idx]
        
        # Get retrieved IDs
        retrieved_ids = [corpus_ids[hit['corpus_id']] for hit in hits]
        
        for k in k_values:
            top_k_retrieved = set(retrieved_ids[:k])
            
            # Check if ANY relevant bill is retrieved
            intersection = len(top_k_retrieved.intersection(gold_ids))
            recall = intersection / len(gold_ids) if len(gold_ids) > 0 else 0
            metrics[f"Recall@{k}"] += recall
            
    # Average
    for k in k_values:
        metrics[f"Recall@{k}"] /= len(query_texts)
        
    return metrics

# Define Models
models_to_test = {
    "BAAI/bge-base-en-v1.5": ["../store/model_testing/baai_1", "../store/model_testing/baai_3", "../store/model_testing/baai_5"],
    "sentence-transformers/all-MiniLM-L6-v2": ["../store/model_testing/minilm_1", "../store/model_testing/minilm_3", "../store/model_testing/minilm_5"],
    "Qwen/Qwen3-Embedding-0.6B": ["../store/model_testing/qwen_0.6_1", "../store/model_testing/qwen_0.6_3"]
}

# Run Evaluation
results_summary = []

for base_model, trained_models in models_to_test.items():
    print(f"\n--- Processing Base Model: {base_model} ---")
    
    # Evaluate Base
    base_metrics = evaluate_model(base_model, bill_texts, bill_ids, claims, ground_truth)
    if base_metrics:
        print(f"Base Model Results: {base_metrics}")
        results_summary.append({"model": base_model, "type": "base", **base_metrics})
    
    # Evaluate Trained
    for trained_model_path in trained_models:
        if os.path.exists(trained_model_path):
            trained_metrics = evaluate_model(trained_model_path, bill_texts, bill_ids, claims, ground_truth)
            if trained_metrics:
                print(f"Trained Model ({os.path.basename(trained_model_path)}) Results: {trained_metrics}")
                results_summary.append({"model": os.path.basename(trained_model_path), "type": "trained", "base": base_model, **trained_metrics})
        else:
            print(f"Trained model path not found: {trained_model_path}")

# Display Summary
print("\n=== Final Summary ===")
df_results = pd.DataFrame(results_summary)
display(df_results)

--- Processing Base Model: BAAI/bge-base-en-v1.5 ---
Evaluating model: BAAI/bge-base-en-v1.5
Encoding corpus...

Batches:   0%|          | 6/10703 [00:59<29:17:16,  9.86s/it]
Exception ignored in: <function tqdm.__del__ at 0x77c36137ce00>
Traceback (most recent call last):
  File "/home/a108983/miniconda3/envs/.venv/lib/python3.11/site-packages/tqdm/std.py", line 1148, in __del__
    self.close()
  File "/home/a108983/miniconda3/envs/.venv/lib/python3.11/site-packages/tqdm/notebook.py", line 279, in close
    self.disp(bar_style='danger', check_delay=False)
    ^^^^^^^^^
AttributeError: 'tqdm_notebook' object has no attribute 'disp'

KeyboardInterrupt: