In [2]:
import pandas as pd

# Load the CSV files
overlap_df = pd.read_csv('../results/overlap_diff_case.csv')
contradiction_df = pd.read_csv('../results/contradiction_diff_case.csv')

# Print the head of both dataframes
print("Overlap Diff Case Head:")
display(overlap_df.head())
print("\nContradiction Diff Case Head:")
display(contradiction_df.head())

Overlap Diff Case Head:

,index1,index2,claim1,claim2,score,name1,name2,docket1,docket2,facts1,api_question1,api_conclusion1,facts2,api_question2,api_conclusion2,body,llm_output,decision,explanation
0,1207,1766,Prosecutors cannot remove potential jurors fro...,Prosecutors cannot remove potential jurors fro...,1.000000,Batson v. Kentucky,Powers v. Ohio,84-6263,89-5011,"Batson, a black man, was on trial charged with...",Did the prosecutor's use of peremptory challen...,The Court found that the prosecutor's actions ...,"Larry Joe Powers, a white male, was indicted o...",Does the Equal Protection Clause of the Fourte...,Yes. Justice Anthony M. Kennedy delivered the ...,"{'messages': [{'role': 'user', 'content': 'You...","```json\n{\n ""explanation"": ""Both claims st...",redundant,Both claims state the same core principle: pro...
1,7481,7490,States can require presidential electors to vo...,States can require presidential electors to vo...,0.996094,Chiafalo v. Washington,Colorado Department of State v. Baca,19-465,19-518,"Under Washington State law, each political par...",Does a state law requiring presidential electo...,A state may constitutionally enforce a preside...,"Michael Baca, Polly Baca, and Robert Nemanich ...","1. Do the petitioners in this case, the presid...","In a per curiam (unsigned) opinion, the Court ...","{'messages': [{'role': 'user', 'content': 'You...","```json\n{\n ""explanation"": ""Both claims es...",redundant,Both claims essentially state the same thing: ...
2,7573,7574,Tribal police can detain and search non-tribal...,Tribal police can detain and search non-tribal...,0.992188,United States v. Cooley,United States v. Cooley,19-1414,19-1414,Joshua James Cooley was parked in his pickup t...,May a police officer for a Native American tri...,A tribal police officer has the authority to d...,Joshua James Cooley was parked in his pickup t...,May a police officer for a Native American tri...,A tribal police officer has the authority to d...,"{'messages': [{'role': 'user', 'content': 'You...","```json\n{\n ""explanation"": ""Both claims es...",redundant,Both claims essentially state the same authori...
3,7574,7575,Tribal police can detain and search non-tribal...,Tribal police can detain and search non-tribal...,0.992188,United States v. Cooley,United States v. Cooley,19-1414,19-1414,Joshua James Cooley was parked in his pickup t...,May a police officer for a Native American tri...,A tribal police officer has the authority to d...,Joshua James Cooley was parked in his pickup t...,May a police officer for a Native American tri...,A tribal police officer has the authority to d...,"{'messages': [{'role': 'user', 'content': 'You...","```json\n{\n ""explanation"": ""Both claims as...",redundant,Both claims assert the authority of tribal pol...
4,1207,6506,Prosecutors cannot remove potential jurors fro...,Prosecutors cannot remove potential jurors fro...,0.992188,Batson v. Kentucky,Foster v. Chatman,84-6263,14-8349,"Batson, a black man, was on trial charged with...",Did the prosecutor's use of peremptory challen...,The Court found that the prosecutor's actions ...,"In 1986, Timothy Tyrone Foster, an 18-year-old...",Was there race-based discrimination of the typ...,The evidence was sufficient to establish that ...,"{'messages': [{'role': 'user', 'content': 'You...","```json\n{\n ""explanation"": ""Both claims ad...",different,Both claims address the legality of removing p...

Contradiction Diff Case Head:

,index1,index2,claim1,claim2,score,name1,name2,docket1,docket2,facts1,api_question1,api_conclusion1,facts2,api_question2,api_conclusion2,body,llm_output,decision,explanation
0,1207,1766,Prosecutors cannot remove potential jurors fro...,Prosecutors cannot remove potential jurors fro...,1.000000,Batson v. Kentucky,Powers v. Ohio,84-6263,89-5011,"Batson, a black man, was on trial charged with...",Did the prosecutor's use of peremptory challen...,The Court found that the prosecutor's actions ...,"Larry Joe Powers, a white male, was indicted o...",Does the Equal Protection Clause of the Fourte...,Yes. Justice Anthony M. Kennedy delivered the ...,"{'messages': [{'role': 'user', 'content': 'You...","```json\n{\n ""explanation"": ""Both claims st...",consistent,Both claims state the same principle: prosecut...
1,7481,7490,States can require presidential electors to vo...,States can require presidential electors to vo...,0.996094,Chiafalo v. Washington,Colorado Department of State v. Baca,19-465,19-518,"Under Washington State law, each political par...",Does a state law requiring presidential electo...,A state may constitutionally enforce a preside...,"Michael Baca, Polly Baca, and Robert Nemanich ...","1. Do the petitioners in this case, the presid...","In a per curiam (unsigned) opinion, the Court ...","{'messages': [{'role': 'user', 'content': 'You...","```json\n{\n ""explanation"": ""Both claims st...",consistent,Both claims state essentially the same thing: ...
2,7573,7574,Tribal police can detain and search non-tribal...,Tribal police can detain and search non-tribal...,0.992188,United States v. Cooley,United States v. Cooley,19-1414,19-1414,Joshua James Cooley was parked in his pickup t...,May a police officer for a Native American tri...,A tribal police officer has the authority to d...,Joshua James Cooley was parked in his pickup t...,May a police officer for a Native American tri...,A tribal police officer has the authority to d...,"{'messages': [{'role': 'user', 'content': 'You...","```json\n{\n ""explanation"": ""Both claims st...",consistent,Both claims state that tribal police can detai...
3,7574,7575,Tribal police can detain and search non-tribal...,Tribal police can detain and search non-tribal...,0.992188,United States v. Cooley,United States v. Cooley,19-1414,19-1414,Joshua James Cooley was parked in his pickup t...,May a police officer for a Native American tri...,A tribal police officer has the authority to d...,Joshua James Cooley was parked in his pickup t...,May a police officer for a Native American tri...,A tribal police officer has the authority to d...,"{'messages': [{'role': 'user', 'content': 'You...","```json\n{\n ""explanation"": ""Both claims st...",consistent,Both claims state that tribal police can detai...
4,1207,6506,Prosecutors cannot remove potential jurors fro...,Prosecutors cannot remove potential jurors fro...,0.992188,Batson v. Kentucky,Foster v. Chatman,84-6263,14-8349,"Batson, a black man, was on trial charged with...",Did the prosecutor's use of peremptory challen...,The Court found that the prosecutor's actions ...,"In 1986, Timothy Tyrone Foster, an 18-year-old...",Was there race-based discrimination of the typ...,The evidence was sufficient to establish that ...,"{'messages': [{'role': 'user', 'content': 'You...","```json\n{\n ""explanation"": ""Both claims st...",consistent,Both claims state that prosecutors cannot remo...

In [6]:
print("Overlap Decision Counts:")
print(overlap_df['decision'].value_counts())
print("\nContradiction Decision Counts:")
print(contradiction_df['decision'].value_counts())

Overlap Decision Counts:
decision
different    12265
redundant     3590
error           19
Name: count, dtype: int64

Contradiction Decision Counts:
decision
consistent       197217
contradiction      1957
error                29
Name: count, dtype: int64

In [8]:
# Filter and print examples for Overlap (Redundant)
redundant_examples = overlap_df[overlap_df['decision'] == 'redundant'].head(10)
print("--- Redundant Examples (Overlap) ---")
for i, row in redundant_examples.iterrows():
    print(f"Example {i+1}:")
    print(f"Case 1: {row['name1']}")
    print(f"Claim 1: {row['claim1']}")
    print(f"Case 2: {row['name2']}")
    print(f"Claim 2: {row['claim2']}")
    print("-" * 20)

# Filter and print examples for Contradiction (Contradiction)
contradiction_examples = contradiction_df[contradiction_df['decision'] == 'contradiction'].head(10)
print("\n--- Contradiction Examples (Contradiction) ---")
for i, row in contradiction_examples.iterrows():
    print(f"Example {i+1}:")
    print(f"Case 1: {row['name1']}")
    print(f"Claim 1: {row['claim1']}")
    print(f"Case 2: {row['name2']}")
    print(f"Claim 2: {row['claim2']}")
    print("-" * 20)

--- Redundant Examples (Overlap) ---
Example 1:
Case 1: Batson v. Kentucky
Claim 1: Prosecutors cannot remove potential jurors from the jury because of their race.
Case 2: Powers v. Ohio
Claim 2: Prosecutors cannot remove potential jurors from a jury because of their race.
--------------------
Example 2:
Case 1: Chiafalo v. Washington
Claim 1: States can require presidential electors to vote for the candidate who won the state's popular vote.
Case 2: Colorado Department of State v. Baca
Claim 2: States can require presidential electors to vote for the candidate who wins the state's popular vote.
--------------------
Example 3:
Case 1: United States v. Cooley
Claim 1: Tribal police can detain and search non-tribal members on reservation public roads for suspected state or federal law violations that threaten the tribe's health.
Case 2: United States v. Cooley
Claim 2: Tribal police can detain and search non-tribal members on reservation public roads for suspected state or federal law violations that threaten the tribe's safety.
--------------------
Example 4:
Case 1: United States v. Cooley
Claim 1: Tribal police can detain and search non-tribal members on reservation public roads for suspected state or federal law violations that threaten the tribe's safety.
Case 2: United States v. Cooley
Claim 2: Tribal police can detain and search non-tribal members on reservation public roads for suspected state or federal law violations that threaten the tribe's economy.
--------------------
Example 7:
Case 1: Richards v. Wisconsin
Claim 1: Police can enter a home without knocking if they reasonably believe announcing would be dangerous.
Case 2: Richards v. Wisconsin
Claim 2: Police can enter a home without knocking if they reasonably believe announcing would be pointless.
--------------------
Example 8:
Case 1: Chicago v. Morales
Claim 1: Laws must clearly explain what behavior is illegal so people know what to avoid.
Case 2: Sessions v. Dimaya
Claim 2: Laws must clearly state what behavior is illegal so people know what to avoid.
--------------------
Example 9:
Case 1: WMCA, Inc. v. Lomenzo
Claim 1: State legislative districts must have approximately equal populations to ensure each vote carries the same weight.
Case 2: Lucas v. Forty-Fourth General Assembly of Colorado
Claim 2: State legislative districts must have nearly equal populations so that each vote carries the same weight.
--------------------
Example 10:
Case 1: United States v. Cooley
Claim 1: Tribal police can detain and search non-tribal members on reservation public roads for suspected state or federal law violations that threaten the tribe's health.
Case 2: United States v. Cooley
Claim 2: Tribal police can detain and search non-tribal members on reservation public roads for suspected state or federal law violations that threaten the tribe's economy.
--------------------
Example 11:
Case 1: Free Enterprise Fund v. Public Company Oversight Board
Claim 1: If part of a law is found unconstitutional, the rest of the law can still be valid as long as it can work without that part.
Case 2: National Federation of Independent Business v. Sebelius
Claim 2: If part of a law is found unconstitutional, the rest of the law can remain valid if it can function without that part.
--------------------
Example 12:
Case 1: Ricci v. Arlington Heights
Claim 1: Police officers can arrest someone without a warrant for a minor offense that only results in a fine if they have probable cause to believe the person committed the offense.
Case 2: Atwater v. City of Lago Vista
Claim 2: Police officers can arrest someone without a warrant for a minor offense that only carries a fine if they have probable cause.
--------------------

--- Contradiction Examples (Contradiction) ---
Example 61:
Case 1: Grimmett v. Brown
Claim 1: The four-year time limit for a civil RICO lawsuit does not start when the fraudulent activity happens.
Case 2: Grimmett v. Brown
Claim 2: The four-year time limit for a civil RICO lawsuit begins when the person discovers the fraud.
--------------------
Example 98:
Case 1: Seminole Tribe of Florida v. Florida
Claim 1: States cannot be sued in federal court without their consent.
Case 2: Franchise Tax Board of California v. Hyatt
Claim 2: States cannot be sued in another state's court without their consent.
--------------------
Example 260:
Case 1: Melendez-Diaz v. Massachusetts
Claim 1: A lab report created for court use cannot be admitted as evidence without the analyst testifying.
Case 2: Bullcoming v. New Mexico
Claim 2: Prosecutors cannot use a lab report in court unless the analyst who performed the test is the one testifying.
--------------------
Example 273:
Case 1: Pennsylvania v. Labron
Claim 1: Police can search a vehicle without a warrant if they have good reason to believe it contains illegal items and the vehicle can be driven away.
Case 2: Maryland v. Dyson
Claim 2: Police can search a car without a warrant even if they had time to get one, as long as they have enough evidence.
--------------------
Example 295:
Case 1: Lawyer v. Department of Justice
Claim 1: Race cannot be the main factor when drawing district lines; other standard districting rules like keeping communities together must be followed.
Case 2: Bethune-Hill v. Virginia Board of Elections
Claim 2: Race can be the main factor in drawing districts even if traditional rules like keeping communities together or making districts compact are followed; proving a conflict between race and those rules isn't required.
--------------------
Example 608:
Case 1: Robbins v. California
Claim 1: Police cannot search closed containers in a vehicle without a warrant, even if they think the container has something illegal.
Case 2: California v. Acevedo
Claim 2: Police can search a container inside a car without a warrant if they have probable cause to believe the container holds evidence.
--------------------
Example 613:
Case 1: El Paso Natural Gas Company v. Neztsosie
Claim 1: Federal courts are the only courts that can decide if a case falls under federal laws requiring federal jurisdiction.
Case 2: Mims v. Arrow Financial Services, LLC
Claim 2: Federal courts can hear cases based on federal laws unless a law specifically says only state courts can handle them.
--------------------
Example 620:
Case 1: Hughes v. United States
Claim 1: A person can apply for a sentence reduction after a guideline change unless the court clearly stated the sentence would have been the same without the guidelines.
Case 2: Koons v. United States
Claim 2: A person can only get a sentence reduction under this law if their original sentence was based on the official sentencing guidelines that were later changed.
--------------------
Example 655:
Case 1: Thornton v. United States
Claim 1: Police can search a vehicle during an arrest to ensure their safety and preserve evidence, even if the person has left the vehicle.
Case 2: Arizona v. Gant
Claim 2: Police can search a vehicle without a warrant after an arrest only if they have reason to believe the person could access the vehicle or that the vehicle contains evidence related to the crime for which they were arrested.
--------------------
Example 717:
Case 1: Gertz v. Robert Welch Inc.
Claim 1: Private individuals do not need to prove the media knew a statement was false or didn't care about the truth to win a libel case.
Case 2: Rosenbloom v. Metromedia, Inc.
Claim 2: To win a libel case about a public matter, the plaintiff must prove the media knew the statement was false or didn't care whether it was true or false.
--------------------

In [10]:
# Filter and print examples for Overlap (Redundant)
redundant_examples = overlap_df[overlap_df['decision'] == 'redundant'].tail(10)
print("--- Redundant Examples (Overlap) ---")
for i, row in redundant_examples.iterrows():
    print(f"Example {i+1}:")
    print(f"Case 1: {row['name1']}")
    print(f"Claim 1: {row['claim1']}")
    print(f"Case 2: {row['name2']}")
    print(f"Claim 2: {row['claim2']}")
    print("-" * 20)

# Filter and print examples for Contradiction (Contradiction)
contradiction_examples = contradiction_df[contradiction_df['decision'] == 'contradiction'].head(10)
print("\n--- Contradiction Examples (Contradiction) ---")
for i, row in contradiction_examples.iterrows():
    print(f"Example {i+1}:")
    print(f"Case 1: {row['name1']}")
    print(f"Claim 1: {row['claim1']}")
    print(f"Case 2: {row['name2']}")
    print(f"Claim 2: {row['claim2']}")
    print("-" * 20)

--- Redundant Examples (Overlap) ---
Example 15758:
Case 1: Breard v. Greene
Claim 1: If a person does not raise a legal issue during their state court trial, federal courts generally will not consider it when reviewing the case later.
Case 2: Cullen v. Pinholster
Claim 2: If a defendant could have presented facts in state court but did not, federal courts cannot use those facts to overturn the conviction.
--------------------
Example 15770:
Case 1: Samuels v. Mackell
Claim 1: Federal courts typically cannot stop a state criminal trial from moving forward just because someone says the law is unconstitutional.
Case 2: Samuels v. Mackell
Claim 2: A person charged under a state law must first have their constitutional claims decided in state court before seeking federal court review.
--------------------
Example 15780:
Case 1: Carroll v. Carman
Claim 1: Police officers are protected from personal liability when there is no clear legal rule about whether their actions were allowed.
Case 2: Sause v. Bauer
Claim 2: Police officers cannot claim qualified immunity unless their actions were legal under all applicable constitutional rules.
--------------------
Example 15784:
Case 1: Hunt v. Washington State Apple Advertising Commission
Claim 1: A law that seems fair but actually hurts out-of-state businesses more than local ones violates federal law.
Case 2: South Central Bell Telephone Company v. Alabama
Claim 2: A state tax that treats companies from other states worse than local companies is unconstitutional.
--------------------
Example 15793:
Case 1: Ohio Forestry Association, Inc. v. Sierra Club
Claim 1: Courts will not hear lawsuits about government plans until the plan has been used to make a specific decision that directly affects someone's rights.
Case 2: Summers v. Earth Island Institute
Claim 2: To challenge a government regulation in court, a person or group must show that the regulation is directly harming their specific interests right now.
--------------------
Example 15834:
Case 1: Crawford v. Nashville and Davidson County, TN
Claim 1: Title VII prohibits employers from firing employees who participate in internal sexual harassment investigations.
Case 2: Crawford v. Nashville and Davidson County, TN
Claim 2: Employees who answer questions about sexual harassment during an internal investigation are protected from retaliation.
--------------------
Example 15838:
Case 1: Summers v. Earth Island Institute
Claim 1: Federal courts can only hear cases where there is an immediate threat of harm caused by a law or regulation.
Case 2: Trump v. New York
Claim 2: To sue in federal court, a person or group must show they have a real and specific harm that is currently happening or will definitely happen very soon.
--------------------
Example 15840:
Case 1: Thompson v. North American Stainless, LP
Claim 1: Employers cannot fire an employee because another person reported discrimination.
Case 2: Thompson v. North American Stainless, LP
Claim 2: Federal law protects employees from retaliation even if they did not personally report discrimination.
--------------------
Example 15841:
Case 1: National Park Hospitality Assn. v. Dept. of the Interior
Claim 1: Legal challenges to government actions must involve actual harm or an immediate threat of harm, not just a theoretical disagreement.
Case 2: DaimlerChrysler Corp. v. Cuno
Claim 2: A person must show a direct personal injury from a government action to have the right to challenge it in court.
--------------------
Example 15852:
Case 1: School District of the City of Grand Rapids v. Ball
Claim 1: Government must stay separate from religious institutions to avoid helping them.
Case 2: Texas Monthly, Inc. v. Bullock
Claim 2: Governments cannot provide tax exemptions exclusively to religious organizations because it amounts to government support of religion.
--------------------

--- Contradiction Examples (Contradiction) ---
Example 61:
Case 1: Grimmett v. Brown
Claim 1: The four-year time limit for a civil RICO lawsuit does not start when the fraudulent activity happens.
Case 2: Grimmett v. Brown
Claim 2: The four-year time limit for a civil RICO lawsuit begins when the person discovers the fraud.
--------------------
Example 98:
Case 1: Seminole Tribe of Florida v. Florida
Claim 1: States cannot be sued in federal court without their consent.
Case 2: Franchise Tax Board of California v. Hyatt
Claim 2: States cannot be sued in another state's court without their consent.
--------------------
Example 260:
Case 1: Melendez-Diaz v. Massachusetts
Claim 1: A lab report created for court use cannot be admitted as evidence without the analyst testifying.
Case 2: Bullcoming v. New Mexico
Claim 2: Prosecutors cannot use a lab report in court unless the analyst who performed the test is the one testifying.
--------------------
Example 273:
Case 1: Pennsylvania v. Labron
Claim 1: Police can search a vehicle without a warrant if they have good reason to believe it contains illegal items and the vehicle can be driven away.
Case 2: Maryland v. Dyson
Claim 2: Police can search a car without a warrant even if they had time to get one, as long as they have enough evidence.
--------------------
Example 295:
Case 1: Lawyer v. Department of Justice
Claim 1: Race cannot be the main factor when drawing district lines; other standard districting rules like keeping communities together must be followed.
Case 2: Bethune-Hill v. Virginia Board of Elections
Claim 2: Race can be the main factor in drawing districts even if traditional rules like keeping communities together or making districts compact are followed; proving a conflict between race and those rules isn't required.
--------------------
Example 608:
Case 1: Robbins v. California
Claim 1: Police cannot search closed containers in a vehicle without a warrant, even if they think the container has something illegal.
Case 2: California v. Acevedo
Claim 2: Police can search a container inside a car without a warrant if they have probable cause to believe the container holds evidence.
--------------------
Example 613:
Case 1: El Paso Natural Gas Company v. Neztsosie
Claim 1: Federal courts are the only courts that can decide if a case falls under federal laws requiring federal jurisdiction.
Case 2: Mims v. Arrow Financial Services, LLC
Claim 2: Federal courts can hear cases based on federal laws unless a law specifically says only state courts can handle them.
--------------------
Example 620:
Case 1: Hughes v. United States
Claim 1: A person can apply for a sentence reduction after a guideline change unless the court clearly stated the sentence would have been the same without the guidelines.
Case 2: Koons v. United States
Claim 2: A person can only get a sentence reduction under this law if their original sentence was based on the official sentencing guidelines that were later changed.
--------------------
Example 655:
Case 1: Thornton v. United States
Claim 1: Police can search a vehicle during an arrest to ensure their safety and preserve evidence, even if the person has left the vehicle.
Case 2: Arizona v. Gant
Claim 2: Police can search a vehicle without a warrant after an arrest only if they have reason to believe the person could access the vehicle or that the vehicle contains evidence related to the crime for which they were arrested.
--------------------
Example 717:
Case 1: Gertz v. Robert Welch Inc.
Claim 1: Private individuals do not need to prove the media knew a statement was false or didn't care about the truth to win a libel case.
Case 2: Rosenbloom v. Metromedia, Inc.
Claim 2: To win a libel case about a public matter, the plaintiff must prove the media knew the statement was false or didn't care whether it was true or false.
--------------------

In [9]:
# Filter and print 10 random examples for Overlap (Redundant)
redundant_df = overlap_df[overlap_df['decision'] == 'redundant']
n_redundant = min(10, len(redundant_df))
redundant_examples_random = redundant_df.sample(n=n_redundant)

print(f"--- {n_redundant} Random Redundant Examples (Overlap) ---")
for idx, (i, row) in enumerate(redundant_examples_random.iterrows()):
    print(f"Example {idx+1}:")
    print(f"Case 1: {row['name1']}")
    print(f"Claim 1: {row['claim1']}")
    print(f"Case 2: {row['name2']}")
    print(f"Claim 2: {row['claim2']}")
    print("-" * 20)

# Filter and print 10 random examples for Contradiction (Contradiction)
contradiction_filtered_df = contradiction_df[contradiction_df['decision'] == 'contradiction']
n_contradiction = min(10, len(contradiction_filtered_df))
contradiction_examples_random = contradiction_filtered_df.sample(n=n_contradiction)

print(f"\n--- {n_contradiction} Random Contradiction Examples (Contradiction) ---")
for idx, (i, row) in enumerate(contradiction_examples_random.iterrows()):
    print(f"Example {idx+1}:")
    print(f"Case 1: {row['name1']}")
    print(f"Claim 1: {row['claim1']}")
    print(f"Case 2: {row['name2']}")
    print(f"Claim 2: {row['claim2']}")
    print("-" * 20)

--- 10 Random Redundant Examples (Overlap) ---
Example 1:
Case 1: United States v. California
Claim 1: The federal government owns the ocean floor beyond three nautical miles from any state's coast.
Case 2: United States v. California
Claim 2: States can only claim ownership of underwater land within three miles of their coast.
--------------------
Example 2:
Case 1: Williams v. Pennsylvania
Claim 1: Judges cannot participate in appeals of cases they previously prosecuted.
Case 2: Williams v. Pennsylvania
Claim 2: A judge who made key decisions like seeking the death penalty in a case must not take part in any appeals of that case.
--------------------
Example 3:
Case 1: Irving Independent School District v. Tatro
Claim 1: Schools must provide health care tasks that can be done by non-medical staff to help children with disabilities attend school.
Case 2: Cedar Rapids Community School Dist. v. Garret F.
Claim 2: Nursing assistance needed for a student to attend school is part of the school's responsibility, even if the tasks are similar to medical procedures.
--------------------
Example 4:
Case 1: Johnson v. Texas
Claim 1: States can structure death penalty sentencing with specific questions for juries as long as the process also lets juries consider any reasons why the defendant should not receive the death penalty.
Case 2: Buchanan v. Angelone
Claim 2: A death sentence is constitutional if the jury is told to consider all evidence, even without details on what might reduce the sentence.
--------------------
Example 5:
Case 1: Cone v. Bell
Claim 1: Prosecutors must share evidence that could change the outcome of a trial or sentencing.
Case 2: Brady v. Maryland
Claim 2: Prosecutors must share evidence that could help the defense. If they hide it, that's against the law.
--------------------
Example 6:
Case 1: Heart of Atlanta Motel, Inc. v. United States
Claim 1: Congress can regulate businesses located in one state if their operations affect trade between states.
Case 2: National Labor Relations Board v. Jones & Laughlin Steel Corporation
Claim 2: Congress cannot regulate activities that have only a minor or remote effect on trade between states.
--------------------
Example 7:
Case 1: Reed v. Reed
Claim 1: Government rules that treat men and women differently must have a good reason; otherwise, they are not allowed.
Case 2: United States v. Virginia
Claim 2: Government actions that treat people differently based on gender must have a very strong reason to be legal.
--------------------
Example 8:
Case 1: V.L. v. E.L.
Claim 1: States must accept court orders from other states if the original court had the power to issue it under its own state's rules.
Case 2: V.L. v. E.L.
Claim 2: A state can refuse to honor another state's court order only if the original court didn't have the power to issue it under its own rules.
--------------------
Example 9:
Case 1: United States v. California
Claim 1: The federal government owns all underwater land beyond three miles from the coastline.
Case 2: United States v. California
Claim 2: States can only claim ownership of underwater land within three miles of their coast.
--------------------
Example 10:
Case 1: United States v. Cotton
Claim 1: An error in the indictment that affects sentencing does not automatically make the sentence invalid if the defendant did not object during the trial.
Case 2: Umans v. United States
Claim 2: If a defense attorney does not object to a jury instruction during the trial, any error in that instruction is not considered plain error.
--------------------

--- 10 Random Contradiction Examples (Contradiction) ---
Example 1:
Case 1: Keyes v. School District No. 1, Denver, Colorado
Claim 1: Public schools cannot intentionally separate students by race; this violates the Constitution.
Case 2: Plessy v. Ferguson
Claim 2: Laws requiring separate facilities for different races are allowed if the facilities are equal.
--------------------
Example 2:
Case 1: Ryder v. United States
Claim 1: When a defendant challenges a judge's appointment as unconstitutional, the court must rule on the challenge and provide appropriate relief if the appointment was invalid.
Case 2: Lamone v. Benisek
Claim 2: There is no clear legal rule that judges can use to determine when political bias in district maps becomes unconstitutional, so courts cannot resolve these disputes.
--------------------
Example 3:
Case 1: National Association of Home Builders v. Defenders of Wildlife
Claim 1: Federal agencies do not need to consider endangered species protections when making decisions that are required by another law and not discretionary.
Case 2: Weyerhaeuser Company v. United States Fish and Wildlife Service
Claim 2: Land cannot be designated as critical habitat under the Endangered Species Act unless it is a habitat for the species, even if the species isn't currently living there.
--------------------
Example 4:
Case 1: John R. Sand & Gravel Company v. United States
Claim 1: Courts can dismiss a Tucker Act case for missing the six-year deadline even if neither party raises the issue.
Case 2: SCA Hygiene Products Aktiebolag v. First Quality Baby Products
Claim 2: If there's a legal deadline for filing a lawsuit, the defense that the plaintiff waited too long cannot be used to stop the case.
--------------------
Example 5:
Case 1: Collins v. Virginia
Claim 1: Police need a warrant to search a vehicle parked in the yard or driveway close to a house.
Case 2: Lange v. California
Claim 2: Police can enter a home without a warrant when chasing someone for a serious crime, but not for minor offenses unless there's an immediate danger.
--------------------
Example 6:
Case 1: Bond v. United States
Claim 1: Federal laws should not apply to everyday crimes handled by states unless Congress explicitly says so.
Case 2: DIRECTV, Inc. v. Imburgia
Claim 2: Federal law takes priority over state law when the two conflict.
--------------------
Example 7:
Case 1: Price Waterhouse v. Hopkins
Claim 1: When an employer says they would have made the same employment decision without discrimination, they must prove it is more likely than not true.
Case 2: Gross v. FBL Financial Services, Inc.
Claim 2: Employers in ADEA cases do not have to prove they would have made the same decision even if age wasn't considered.
--------------------
Example 8:
Case 1: Allen v. Siebert
Claim 1: Missing a deadline to file a legal claim means the court cannot consider the case.
Case 2: Sebelius v. Auburn Regional Medical Center
Claim 2: Courts cannot extend government claim deadlines just because it seems fair unless Congress has specifically allowed it.
--------------------
Example 9:
Case 1: Office of Personnel Management v. Richmond
Claim 1: The U.S. Constitution requires that government payments can only be made if a law specifically allows it, so mistakes by employees don't change this rule.
Case 2: Salazar v. Ramah Navajo Chapter
Claim 2: The federal government must pay the full amount promised in a contract, even if the total cost exceeds the money Congress provided for that purpose.
--------------------
Example 10:
Case 1: Brown v. Legal Foundation of Washington
Claim 1: The government does not have to pay compensation when there is no financial loss to a property owner.
Case 2: Horne v. Department of Agriculture
Claim 2: The government must pay for taking any kind of property, whether it's land or personal items.
--------------------