In [1]:
import pandas as pd

# Load the CSV files
overlap_df = pd.read_csv('../results/overlap_diff_case.csv')
contradiction_df = pd.read_csv('../results/contradiction_diff_case.csv')

# Print the head of both dataframes
print("Overlap Diff Case Head:")
display(overlap_df.head())
print("\nContradiction Diff Case Head:")
display(contradiction_df.head())

Overlap Diff Case Head:

,index1,index2,claim1,claim2,score,name1,name2,docket1,docket2,facts1,api_question1,api_conclusion1,facts2,api_question2,api_conclusion2,body,llm_output,decision,explanation
0,1207,1766,Prosecutors cannot remove potential jurors fro...,Prosecutors cannot remove potential jurors fro...,1.000000,Batson v. Kentucky,Powers v. Ohio,84-6263,89-5011,"Batson, a black man, was on trial charged with...",Did the prosecutor's use of peremptory challen...,The Court found that the prosecutor's actions ...,"Larry Joe Powers, a white male, was indicted o...",Does the Equal Protection Clause of the Fourte...,Yes. Justice Anthony M. Kennedy delivered the ...,"{'messages': [{'role': 'user', 'content': 'You...","```json\n{\n ""explanation"": ""Both claims st...",redundant,Both claims state the same core principle: pro...
1,7481,7490,States can require presidential electors to vo...,States can require presidential electors to vo...,0.996094,Chiafalo v. Washington,Colorado Department of State v. Baca,19-465,19-518,"Under Washington State law, each political par...",Does a state law requiring presidential electo...,A state may constitutionally enforce a preside...,"Michael Baca, Polly Baca, and Robert Nemanich ...","1. Do the petitioners in this case, the presid...","In a per curiam (unsigned) opinion, the Court ...","{'messages': [{'role': 'user', 'content': 'You...","```json\n{\n ""explanation"": ""Both claims es...",redundant,Both claims essentially state the same thing: ...
2,7573,7574,Tribal police can detain and search non-tribal...,Tribal police can detain and search non-tribal...,0.992188,United States v. Cooley,United States v. Cooley,19-1414,19-1414,Joshua James Cooley was parked in his pickup t...,May a police officer for a Native American tri...,A tribal police officer has the authority to d...,Joshua James Cooley was parked in his pickup t...,May a police officer for a Native American tri...,A tribal police officer has the authority to d...,"{'messages': [{'role': 'user', 'content': 'You...","```json\n{\n ""explanation"": ""Both claims es...",redundant,Both claims essentially state the same authori...
3,7574,7575,Tribal police can detain and search non-tribal...,Tribal police can detain and search non-tribal...,0.992188,United States v. Cooley,United States v. Cooley,19-1414,19-1414,Joshua James Cooley was parked in his pickup t...,May a police officer for a Native American tri...,A tribal police officer has the authority to d...,Joshua James Cooley was parked in his pickup t...,May a police officer for a Native American tri...,A tribal police officer has the authority to d...,"{'messages': [{'role': 'user', 'content': 'You...","```json\n{\n ""explanation"": ""Both claims as...",redundant,Both claims assert the authority of tribal pol...
4,1207,6506,Prosecutors cannot remove potential jurors fro...,Prosecutors cannot remove potential jurors fro...,0.992188,Batson v. Kentucky,Foster v. Chatman,84-6263,14-8349,"Batson, a black man, was on trial charged with...",Did the prosecutor's use of peremptory challen...,The Court found that the prosecutor's actions ...,"In 1986, Timothy Tyrone Foster, an 18-year-old...",Was there race-based discrimination of the typ...,The evidence was sufficient to establish that ...,"{'messages': [{'role': 'user', 'content': 'You...","```json\n{\n ""explanation"": ""Both claims ad...",different,Both claims address the legality of removing p...

Contradiction Diff Case Head:

,index1,index2,claim1,claim2,score,name1,name2,docket1,docket2,facts1,api_question1,api_conclusion1,facts2,api_question2,api_conclusion2,body,llm_output,decision,explanation
0,1207,1766,Prosecutors cannot remove potential jurors fro...,Prosecutors cannot remove potential jurors fro...,1.000000,Batson v. Kentucky,Powers v. Ohio,84-6263,89-5011,"Batson, a black man, was on trial charged with...",Did the prosecutor's use of peremptory challen...,The Court found that the prosecutor's actions ...,"Larry Joe Powers, a white male, was indicted o...",Does the Equal Protection Clause of the Fourte...,Yes. Justice Anthony M. Kennedy delivered the ...,"{'messages': [{'role': 'user', 'content': 'You...","```json\n{\n ""explanation"": ""Both claims st...",consistent,Both claims state the same principle: prosecut...
1,7481,7490,States can require presidential electors to vo...,States can require presidential electors to vo...,0.996094,Chiafalo v. Washington,Colorado Department of State v. Baca,19-465,19-518,"Under Washington State law, each political par...",Does a state law requiring presidential electo...,A state may constitutionally enforce a preside...,"Michael Baca, Polly Baca, and Robert Nemanich ...","1. Do the petitioners in this case, the presid...","In a per curiam (unsigned) opinion, the Court ...","{'messages': [{'role': 'user', 'content': 'You...","```json\n{\n ""explanation"": ""Both claims st...",consistent,Both claims state essentially the same thing: ...
2,7573,7574,Tribal police can detain and search non-tribal...,Tribal police can detain and search non-tribal...,0.992188,United States v. Cooley,United States v. Cooley,19-1414,19-1414,Joshua James Cooley was parked in his pickup t...,May a police officer for a Native American tri...,A tribal police officer has the authority to d...,Joshua James Cooley was parked in his pickup t...,May a police officer for a Native American tri...,A tribal police officer has the authority to d...,"{'messages': [{'role': 'user', 'content': 'You...","```json\n{\n ""explanation"": ""Both claims st...",consistent,Both claims state that tribal police can detai...
3,7574,7575,Tribal police can detain and search non-tribal...,Tribal police can detain and search non-tribal...,0.992188,United States v. Cooley,United States v. Cooley,19-1414,19-1414,Joshua James Cooley was parked in his pickup t...,May a police officer for a Native American tri...,A tribal police officer has the authority to d...,Joshua James Cooley was parked in his pickup t...,May a police officer for a Native American tri...,A tribal police officer has the authority to d...,"{'messages': [{'role': 'user', 'content': 'You...","```json\n{\n ""explanation"": ""Both claims st...",consistent,Both claims state that tribal police can detai...
4,1207,6506,Prosecutors cannot remove potential jurors fro...,Prosecutors cannot remove potential jurors fro...,0.992188,Batson v. Kentucky,Foster v. Chatman,84-6263,14-8349,"Batson, a black man, was on trial charged with...",Did the prosecutor's use of peremptory challen...,The Court found that the prosecutor's actions ...,"In 1986, Timothy Tyrone Foster, an 18-year-old...",Was there race-based discrimination of the typ...,The evidence was sufficient to establish that ...,"{'messages': [{'role': 'user', 'content': 'You...","```json\n{\n ""explanation"": ""Both claims st...",consistent,Both claims state that prosecutors cannot remo...

In [2]:
print("Overlap Decision Counts:")
print(overlap_df['decision'].value_counts(normalize=True))
print(overlap_df['decision'].value_counts())
print("\nContradiction Decision Counts:")
print(contradiction_df['decision'].value_counts(normalize=True))
print(contradiction_df['decision'].value_counts())
print(3590/(12265+3590+19))
print(1957/(197217+1957+29))

Overlap Decision Counts:
decision
different    0.772647
redundant    0.226156
error        0.001197
Name: proportion, dtype: float64
decision
different    12265
redundant     3590
error           19
Name: count, dtype: int64

Contradiction Decision Counts:
decision
consistent       0.990030
contradiction    0.009824
error            0.000146
Name: proportion, dtype: float64
decision
consistent       197217
contradiction      1957
error                29
Name: count, dtype: int64
0.2261559783293436
0.00982414923470028

In [8]:
# Filter and print examples for Overlap (Redundant)
redundant_examples = overlap_df[overlap_df['decision'] == 'redundant'].head(10)
print("--- Redundant Examples (Overlap) ---")
for i, row in redundant_examples.iterrows():
    print(f"Example {i+1}:")
    print(f"Case 1: {row['name1']}")
    print(f"Claim 1: {row['claim1']}")
    print(f"Case 2: {row['name2']}")
    print(f"Claim 2: {row['claim2']}")
    print("-" * 20)

# Filter and print examples for Contradiction (Contradiction)
contradiction_examples = contradiction_df[contradiction_df['decision'] == 'contradiction'].head(10)
print("\n--- Contradiction Examples (Contradiction) ---")
for i, row in contradiction_examples.iterrows():
    print(f"Example {i+1}:")
    print(f"Case 1: {row['name1']}")
    print(f"Claim 1: {row['claim1']}")
    print(f"Case 2: {row['name2']}")
    print(f"Claim 2: {row['claim2']}")
    print("-" * 20)

--- Redundant Examples (Overlap) ---
Example 1:
Case 1: Batson v. Kentucky
Claim 1: Prosecutors cannot remove potential jurors from the jury because of their race.
Case 2: Powers v. Ohio
Claim 2: Prosecutors cannot remove potential jurors from a jury because of their race.
--------------------
Example 2:
Case 1: Chiafalo v. Washington
Claim 1: States can require presidential electors to vote for the candidate who won the state's popular vote.
Case 2: Colorado Department of State v. Baca
Claim 2: States can require presidential electors to vote for the candidate who wins the state's popular vote.
--------------------
Example 3:
Case 1: United States v. Cooley
Claim 1: Tribal police can detain and search non-tribal members on reservation public roads for suspected state or federal law violations that threaten the tribe's health.
Case 2: United States v. Cooley
Claim 2: Tribal police can detain and search non-tribal members on reservation public roads for suspected state or federal law violations that threaten the tribe's safety.
--------------------
Example 4:
Case 1: United States v. Cooley
Claim 1: Tribal police can detain and search non-tribal members on reservation public roads for suspected state or federal law violations that threaten the tribe's safety.
Case 2: United States v. Cooley
Claim 2: Tribal police can detain and search non-tribal members on reservation public roads for suspected state or federal law violations that threaten the tribe's economy.
--------------------
Example 7:
Case 1: Richards v. Wisconsin
Claim 1: Police can enter a home without knocking if they reasonably believe announcing would be dangerous.
Case 2: Richards v. Wisconsin
Claim 2: Police can enter a home without knocking if they reasonably believe announcing would be pointless.
--------------------
Example 8:
Case 1: Chicago v. Morales
Claim 1: Laws must clearly explain what behavior is illegal so people know what to avoid.
Case 2: Sessions v. Dimaya
Claim 2: Laws must clearly state what behavior is illegal so people know what to avoid.
--------------------
Example 9:
Case 1: WMCA, Inc. v. Lomenzo
Claim 1: State legislative districts must have approximately equal populations to ensure each vote carries the same weight.
Case 2: Lucas v. Forty-Fourth General Assembly of Colorado
Claim 2: State legislative districts must have nearly equal populations so that each vote carries the same weight.
--------------------
Example 10:
Case 1: United States v. Cooley
Claim 1: Tribal police can detain and search non-tribal members on reservation public roads for suspected state or federal law violations that threaten the tribe's health.
Case 2: United States v. Cooley
Claim 2: Tribal police can detain and search non-tribal members on reservation public roads for suspected state or federal law violations that threaten the tribe's economy.
--------------------
Example 11:
Case 1: Free Enterprise Fund v. Public Company Oversight Board
Claim 1: If part of a law is found unconstitutional, the rest of the law can still be valid as long as it can work without that part.
Case 2: National Federation of Independent Business v. Sebelius
Claim 2: If part of a law is found unconstitutional, the rest of the law can remain valid if it can function without that part.
--------------------
Example 12:
Case 1: Ricci v. Arlington Heights
Claim 1: Police officers can arrest someone without a warrant for a minor offense that only results in a fine if they have probable cause to believe the person committed the offense.
Case 2: Atwater v. City of Lago Vista
Claim 2: Police officers can arrest someone without a warrant for a minor offense that only carries a fine if they have probable cause.
--------------------

--- Contradiction Examples (Contradiction) ---
Example 61:
Case 1: Grimmett v. Brown
Claim 1: The four-year time limit for a civil RICO lawsuit does not start when the fraudulent activity happens.
Case 2: Grimmett v. Brown
Claim 2: The four-year time limit for a civil RICO lawsuit begins when the person discovers the fraud.
--------------------
Example 98:
Case 1: Seminole Tribe of Florida v. Florida
Claim 1: States cannot be sued in federal court without their consent.
Case 2: Franchise Tax Board of California v. Hyatt
Claim 2: States cannot be sued in another state's court without their consent.
--------------------
Example 260:
Case 1: Melendez-Diaz v. Massachusetts
Claim 1: A lab report created for court use cannot be admitted as evidence without the analyst testifying.
Case 2: Bullcoming v. New Mexico
Claim 2: Prosecutors cannot use a lab report in court unless the analyst who performed the test is the one testifying.
--------------------
Example 273:
Case 1: Pennsylvania v. Labron
Claim 1: Police can search a vehicle without a warrant if they have good reason to believe it contains illegal items and the vehicle can be driven away.
Case 2: Maryland v. Dyson
Claim 2: Police can search a car without a warrant even if they had time to get one, as long as they have enough evidence.
--------------------
Example 295:
Case 1: Lawyer v. Department of Justice
Claim 1: Race cannot be the main factor when drawing district lines; other standard districting rules like keeping communities together must be followed.
Case 2: Bethune-Hill v. Virginia Board of Elections
Claim 2: Race can be the main factor in drawing districts even if traditional rules like keeping communities together or making districts compact are followed; proving a conflict between race and those rules isn't required.
--------------------
Example 608:
Case 1: Robbins v. California
Claim 1: Police cannot search closed containers in a vehicle without a warrant, even if they think the container has something illegal.
Case 2: California v. Acevedo
Claim 2: Police can search a container inside a car without a warrant if they have probable cause to believe the container holds evidence.
--------------------
Example 613:
Case 1: El Paso Natural Gas Company v. Neztsosie
Claim 1: Federal courts are the only courts that can decide if a case falls under federal laws requiring federal jurisdiction.
Case 2: Mims v. Arrow Financial Services, LLC
Claim 2: Federal courts can hear cases based on federal laws unless a law specifically says only state courts can handle them.
--------------------
Example 620:
Case 1: Hughes v. United States
Claim 1: A person can apply for a sentence reduction after a guideline change unless the court clearly stated the sentence would have been the same without the guidelines.
Case 2: Koons v. United States
Claim 2: A person can only get a sentence reduction under this law if their original sentence was based on the official sentencing guidelines that were later changed.
--------------------
Example 655:
Case 1: Thornton v. United States
Claim 1: Police can search a vehicle during an arrest to ensure their safety and preserve evidence, even if the person has left the vehicle.
Case 2: Arizona v. Gant
Claim 2: Police can search a vehicle without a warrant after an arrest only if they have reason to believe the person could access the vehicle or that the vehicle contains evidence related to the crime for which they were arrested.
--------------------
Example 717:
Case 1: Gertz v. Robert Welch Inc.
Claim 1: Private individuals do not need to prove the media knew a statement was false or didn't care about the truth to win a libel case.
Case 2: Rosenbloom v. Metromedia, Inc.
Claim 2: To win a libel case about a public matter, the plaintiff must prove the media knew the statement was false or didn't care whether it was true or false.
--------------------

In [12]:
# Filter and print examples for Overlap (Redundant)
redundant_examples = overlap_df[overlap_df['decision'] == 'redundant'].tail(10)
print("--- Redundant Examples (Overlap) ---")
for i, row in redundant_examples.iterrows():
    print(f"Example {i+1}:")
    print(f"Case 1: {row['name1']}")
    print(f"Claim 1: {row['claim1']}")
    print(f"Case 2: {row['name2']}")
    print(f"Claim 2: {row['claim2']}")
    print("-" * 20)

# Filter and print examples for Contradiction (Contradiction)
contradiction_examples = contradiction_df[contradiction_df['decision'] == 'contradiction'].tail(10)
print("\n--- Contradiction Examples (Contradiction) ---")
for i, row in contradiction_examples.iterrows():
    print(f"Example {i+1}:")
    print(f"Case 1: {row['name1']}")
    print(f"Claim 1: {row['claim1']}")
    print(f"Case 2: {row['name2']}")
    print(f"Claim 2: {row['claim2']}")
    print("-" * 20)

--- Redundant Examples (Overlap) ---
Example 15758:
Case 1: Breard v. Greene
Claim 1: If a person does not raise a legal issue during their state court trial, federal courts generally will not consider it when reviewing the case later.
Case 2: Cullen v. Pinholster
Claim 2: If a defendant could have presented facts in state court but did not, federal courts cannot use those facts to overturn the conviction.
--------------------
Example 15770:
Case 1: Samuels v. Mackell
Claim 1: Federal courts typically cannot stop a state criminal trial from moving forward just because someone says the law is unconstitutional.
Case 2: Samuels v. Mackell
Claim 2: A person charged under a state law must first have their constitutional claims decided in state court before seeking federal court review.
--------------------
Example 15780:
Case 1: Carroll v. Carman
Claim 1: Police officers are protected from personal liability when there is no clear legal rule about whether their actions were allowed.
Case 2: Sause v. Bauer
Claim 2: Police officers cannot claim qualified immunity unless their actions were legal under all applicable constitutional rules.
--------------------
Example 15784:
Case 1: Hunt v. Washington State Apple Advertising Commission
Claim 1: A law that seems fair but actually hurts out-of-state businesses more than local ones violates federal law.
Case 2: South Central Bell Telephone Company v. Alabama
Claim 2: A state tax that treats companies from other states worse than local companies is unconstitutional.
--------------------
Example 15793:
Case 1: Ohio Forestry Association, Inc. v. Sierra Club
Claim 1: Courts will not hear lawsuits about government plans until the plan has been used to make a specific decision that directly affects someone's rights.
Case 2: Summers v. Earth Island Institute
Claim 2: To challenge a government regulation in court, a person or group must show that the regulation is directly harming their specific interests right now.
--------------------
Example 15834:
Case 1: Crawford v. Nashville and Davidson County, TN
Claim 1: Title VII prohibits employers from firing employees who participate in internal sexual harassment investigations.
Case 2: Crawford v. Nashville and Davidson County, TN
Claim 2: Employees who answer questions about sexual harassment during an internal investigation are protected from retaliation.
--------------------
Example 15838:
Case 1: Summers v. Earth Island Institute
Claim 1: Federal courts can only hear cases where there is an immediate threat of harm caused by a law or regulation.
Case 2: Trump v. New York
Claim 2: To sue in federal court, a person or group must show they have a real and specific harm that is currently happening or will definitely happen very soon.
--------------------
Example 15840:
Case 1: Thompson v. North American Stainless, LP
Claim 1: Employers cannot fire an employee because another person reported discrimination.
Case 2: Thompson v. North American Stainless, LP
Claim 2: Federal law protects employees from retaliation even if they did not personally report discrimination.
--------------------
Example 15841:
Case 1: National Park Hospitality Assn. v. Dept. of the Interior
Claim 1: Legal challenges to government actions must involve actual harm or an immediate threat of harm, not just a theoretical disagreement.
Case 2: DaimlerChrysler Corp. v. Cuno
Claim 2: A person must show a direct personal injury from a government action to have the right to challenge it in court.
--------------------
Example 15852:
Case 1: School District of the City of Grand Rapids v. Ball
Claim 1: Government must stay separate from religious institutions to avoid helping them.
Case 2: Texas Monthly, Inc. v. Bullock
Claim 2: Governments cannot provide tax exemptions exclusively to religious organizations because it amounts to government support of religion.
--------------------

--- Contradiction Examples (Contradiction) ---
Example 197060:
Case 1: Murray v. United States
Claim 1: Evidence found during a lawful search warrant is allowed in court if the warrant was based on information that was legally obtained and not connected to any illegal police actions.
Case 2: Vale v. Louisiana
Claim 2: Police need a warrant to search a home for evidence, even if they have an arrest warrant for the person living there.
--------------------
Example 197194:
Case 1: Purcell v. Gonzalez
Claim 1: Federal election laws take priority over state laws that conflict with them.
Case 2: Bond v. United States
Claim 2: Federal laws that take away powers reserved for states are unconstitutional and can be challenged by anyone affected.
--------------------
Example 197199:
Case 1: Brown v. Illinois
Claim 1: Even if a confession is voluntary, it can't be used in court if it came from an illegal arrest.
Case 2: Devenpeck v. Alford
Claim 2: An officer's reasons for making an arrest don't affect whether the arrest was legal as long as the facts known to them supported probable cause for some crime.
--------------------
Example 197876:
Case 1: Witters v. Washington Department of Services for the Blind
Claim 1: Public funds can be used for religious education when the aid is given to individuals who decide how to spend it, and the program is available to all regardless of religion.
Case 2: Texas Monthly, Inc. v. Bullock
Claim 2: Tax laws that exempt religious publications but not nonreligious ones violate the Constitution's protection for a free press by discriminating based on content.
--------------------
Example 197921:
Case 1: National Socialist Party of America v. Village of Skokie
Claim 1: The U.S. Supreme Court can review cases where lower courts block free speech, even if the lower courts haven't finished their case.
Case 2: National Park Hospitality Assn. v. Dept. of the Interior
Claim 2: A government agency's statement about how it interprets a law cannot be challenged in court until it is applied in an actual case.
--------------------
Example 197970:
Case 1: Jerome B. Grubart, Inc. v. Great Lakes Dredge & Dock Company
Claim 1: How long ago or how far away the damage occurred does not affect whether federal courts have jurisdiction.
Case 2: Summers v. Earth Island Institute
Claim 2: Federal courts can only hear cases where there is an immediate threat of harm caused by a law or regulation.
--------------------
Example 198364:
Case 1: Burwell v. Hobby Lobby Stores
Claim 1: The government must use the least restrictive way to achieve its goals when a law conflicts with religious beliefs.
Case 2: Gallagher v. Crown Kosher Super Market of Massachusetts, Inc.
Claim 2: Laws that apply to all stores equally, such as requiring Sunday closures, do not violate the Constitution's requirement for equal treatment just because they affect some religious groups more.
--------------------
Example 198992:
Case 1: Exxon Corporation v. Eagerton
Claim 1: Laws that treat different groups differently are allowed if there is a reasonable reason for the difference, such as protecting consumers from high prices.
Case 2: International Union, United Automobile, Aerospace & Agricultural Implement Workers of America, UAW
Claim 2: Policies that discriminate based on gender are illegal even if the employer's intentions are protective.
--------------------
Example 199099:
Case 1: Mach Mining, LLC v. Equal Employment Opportunity Commission
Claim 1: Courts cannot review how hard the agency tried to negotiate or whether the settlement offers were fair.
Case 2: Department of Commerce v. New York
Claim 2: If an agency's explanation for a decision doesn't match the facts, courts can send the case back for the agency to explain it properly.
--------------------
Example 199112:
Case 1: Ybarra v. Illinois
Claim 1: Police cannot search a person's body or belongings just because they are in a location where a search warrant is being executed unless there is specific evidence linking them to the crime.
Case 2: Florence v. Board of Chosen Freeholders of the County of Burlington
Claim 2: Jails can perform a strip search on anyone who will be staying with other inmates without needing any specific reason.
--------------------

In [9]:
# Filter and print 10 random examples for Overlap (Redundant)
redundant_df = overlap_df[overlap_df['decision'] == 'redundant']
n_redundant = min(10, len(redundant_df))
redundant_examples_random = redundant_df.sample(n=n_redundant)

print(f"--- {n_redundant} Random Redundant Examples (Overlap) ---")
for idx, (i, row) in enumerate(redundant_examples_random.iterrows()):
    print(f"Example {idx+1}:")
    print(f"Case 1: {row['name1']}")
    print(f"Claim 1: {row['claim1']}")
    print(f"Case 2: {row['name2']}")
    print(f"Claim 2: {row['claim2']}")
    print("-" * 20)

# Filter and print 10 random examples for Contradiction (Contradiction)
contradiction_filtered_df = contradiction_df[contradiction_df['decision'] == 'contradiction']
n_contradiction = min(10, len(contradiction_filtered_df))
contradiction_examples_random = contradiction_filtered_df.sample(n=n_contradiction)

print(f"\n--- {n_contradiction} Random Contradiction Examples (Contradiction) ---")
for idx, (i, row) in enumerate(contradiction_examples_random.iterrows()):
    print(f"Example {idx+1}:")
    print(f"Case 1: {row['name1']}")
    print(f"Claim 1: {row['claim1']}")
    print(f"Case 2: {row['name2']}")
    print(f"Claim 2: {row['claim2']}")
    print("-" * 20)

--- 10 Random Redundant Examples (Overlap) ---
Example 1:
Case 1: United States v. California
Claim 1: The federal government owns the ocean floor beyond three nautical miles from any state's coast.
Case 2: United States v. California
Claim 2: States can only claim ownership of underwater land within three miles of their coast.
--------------------
Example 2:
Case 1: Williams v. Pennsylvania
Claim 1: Judges cannot participate in appeals of cases they previously prosecuted.
Case 2: Williams v. Pennsylvania
Claim 2: A judge who made key decisions like seeking the death penalty in a case must not take part in any appeals of that case.
--------------------
Example 3:
Case 1: Irving Independent School District v. Tatro
Claim 1: Schools must provide health care tasks that can be done by non-medical staff to help children with disabilities attend school.
Case 2: Cedar Rapids Community School Dist. v. Garret F.
Claim 2: Nursing assistance needed for a student to attend school is part of the school's responsibility, even if the tasks are similar to medical procedures.
--------------------
Example 4:
Case 1: Johnson v. Texas
Claim 1: States can structure death penalty sentencing with specific questions for juries as long as the process also lets juries consider any reasons why the defendant should not receive the death penalty.
Case 2: Buchanan v. Angelone
Claim 2: A death sentence is constitutional if the jury is told to consider all evidence, even without details on what might reduce the sentence.
--------------------
Example 5:
Case 1: Cone v. Bell
Claim 1: Prosecutors must share evidence that could change the outcome of a trial or sentencing.
Case 2: Brady v. Maryland
Claim 2: Prosecutors must share evidence that could help the defense. If they hide it, that's against the law.
--------------------
Example 6:
Case 1: Heart of Atlanta Motel, Inc. v. United States
Claim 1: Congress can regulate businesses located in one state if their operations affect trade between states.
Case 2: National Labor Relations Board v. Jones & Laughlin Steel Corporation
Claim 2: Congress cannot regulate activities that have only a minor or remote effect on trade between states.
--------------------
Example 7:
Case 1: Reed v. Reed
Claim 1: Government rules that treat men and women differently must have a good reason; otherwise, they are not allowed.
Case 2: United States v. Virginia
Claim 2: Government actions that treat people differently based on gender must have a very strong reason to be legal.
--------------------
Example 8:
Case 1: V.L. v. E.L.
Claim 1: States must accept court orders from other states if the original court had the power to issue it under its own state's rules.
Case 2: V.L. v. E.L.
Claim 2: A state can refuse to honor another state's court order only if the original court didn't have the power to issue it under its own rules.
--------------------
Example 9:
Case 1: United States v. California
Claim 1: The federal government owns all underwater land beyond three miles from the coastline.
Case 2: United States v. California
Claim 2: States can only claim ownership of underwater land within three miles of their coast.
--------------------
Example 10:
Case 1: United States v. Cotton
Claim 1: An error in the indictment that affects sentencing does not automatically make the sentence invalid if the defendant did not object during the trial.
Case 2: Umans v. United States
Claim 2: If a defense attorney does not object to a jury instruction during the trial, any error in that instruction is not considered plain error.
--------------------

--- 10 Random Contradiction Examples (Contradiction) ---
Example 1:
Case 1: Keyes v. School District No. 1, Denver, Colorado
Claim 1: Public schools cannot intentionally separate students by race; this violates the Constitution.
Case 2: Plessy v. Ferguson
Claim 2: Laws requiring separate facilities for different races are allowed if the facilities are equal.
--------------------
Example 2:
Case 1: Ryder v. United States
Claim 1: When a defendant challenges a judge's appointment as unconstitutional, the court must rule on the challenge and provide appropriate relief if the appointment was invalid.
Case 2: Lamone v. Benisek
Claim 2: There is no clear legal rule that judges can use to determine when political bias in district maps becomes unconstitutional, so courts cannot resolve these disputes.
--------------------
Example 3:
Case 1: National Association of Home Builders v. Defenders of Wildlife
Claim 1: Federal agencies do not need to consider endangered species protections when making decisions that are required by another law and not discretionary.
Case 2: Weyerhaeuser Company v. United States Fish and Wildlife Service
Claim 2: Land cannot be designated as critical habitat under the Endangered Species Act unless it is a habitat for the species, even if the species isn't currently living there.
--------------------
Example 4:
Case 1: John R. Sand & Gravel Company v. United States
Claim 1: Courts can dismiss a Tucker Act case for missing the six-year deadline even if neither party raises the issue.
Case 2: SCA Hygiene Products Aktiebolag v. First Quality Baby Products
Claim 2: If there's a legal deadline for filing a lawsuit, the defense that the plaintiff waited too long cannot be used to stop the case.
--------------------
Example 5:
Case 1: Collins v. Virginia
Claim 1: Police need a warrant to search a vehicle parked in the yard or driveway close to a house.
Case 2: Lange v. California
Claim 2: Police can enter a home without a warrant when chasing someone for a serious crime, but not for minor offenses unless there's an immediate danger.
--------------------
Example 6:
Case 1: Bond v. United States
Claim 1: Federal laws should not apply to everyday crimes handled by states unless Congress explicitly says so.
Case 2: DIRECTV, Inc. v. Imburgia
Claim 2: Federal law takes priority over state law when the two conflict.
--------------------
Example 7:
Case 1: Price Waterhouse v. Hopkins
Claim 1: When an employer says they would have made the same employment decision without discrimination, they must prove it is more likely than not true.
Case 2: Gross v. FBL Financial Services, Inc.
Claim 2: Employers in ADEA cases do not have to prove they would have made the same decision even if age wasn't considered.
--------------------
Example 8:
Case 1: Allen v. Siebert
Claim 1: Missing a deadline to file a legal claim means the court cannot consider the case.
Case 2: Sebelius v. Auburn Regional Medical Center
Claim 2: Courts cannot extend government claim deadlines just because it seems fair unless Congress has specifically allowed it.
--------------------
Example 9:
Case 1: Office of Personnel Management v. Richmond
Claim 1: The U.S. Constitution requires that government payments can only be made if a law specifically allows it, so mistakes by employees don't change this rule.
Case 2: Salazar v. Ramah Navajo Chapter
Claim 2: The federal government must pay the full amount promised in a contract, even if the total cost exceeds the money Congress provided for that purpose.
--------------------
Example 10:
Case 1: Brown v. Legal Foundation of Washington
Claim 1: The government does not have to pay compensation when there is no financial loss to a property owner.
Case 2: Horne v. Department of Agriculture
Claim 2: The government must pay for taking any kind of property, whether it's land or personal items.
--------------------

In [3]:
import pandas as pd

# Load the CSV files
overlap_df = pd.read_csv('../results/factual_claims_resolved_overlaps.csv')
contradiction_df = pd.read_csv('../results/factual_claims_resolved_contradictions.csv')

# Print the head of both dataframes
print("Overlap Diff Case Head:")
display(overlap_df.head())
print("\nContradiction Diff Case Head:")
display(contradiction_df.head())

Overlap Diff Case Head:

,index1,index2,claim1,claim2,score,name1,name2,docket1,docket2,llm_output,...,explanation,facts1,api_question1,api_conclusion1,facts2,api_question2,api_conclusion2,resolution_decision,merged_claim,reasoning
0,1207,1766,Prosecutors cannot remove potential jurors fro...,Prosecutors cannot remove potential jurors fro...,1.000000,Batson v. Kentucky,Powers v. Ohio,84-6263,89-5011,"```json\n{\n ""reasoning"": ""Both claims stat...",...,Both claims state the same core principle: pro...,"Batson, a black man, was on trial charged with...",Did the prosecutor's use of peremptory challen...,The Court found that the prosecutor's actions ...,"Larry Joe Powers, a white male, was indicted o...",Does the Equal Protection Clause of the Fourte...,Yes. Justice Anthony M. Kennedy delivered the ...,keep_1,NaN,Both claims state the same legal principle: pr...
1,7481,7490,States can require presidential electors to vo...,States can require presidential electors to vo...,0.996094,Chiafalo v. Washington,Colorado Department of State v. Baca,19-465,19-518,"```json\n{\n ""reasoning"": ""Both claims stat...",...,Both claims essentially state the same thing: ...,"Under Washington State law, each political par...",Does a state law requiring presidential electo...,A state may constitutionally enforce a preside...,"Michael Baca, Polly Baca, and Robert Nemanich ...","1. Do the petitioners in this case, the presid...","In a per curiam (unsigned) opinion, the Court ...",keep_1,NaN,Both claims state the same legal principle: st...
2,2798,6855,Laws must clearly explain what behavior is ill...,Laws must clearly state what behavior is illeg...,0.992188,Chicago v. Morales,Sessions v. Dimaya,97-1121,15-1498,"```json\n{\n ""reasoning"": ""Both claims expr...",...,Both claims express the same fundamental princ...,Chicago's Gang Congregation Ordinance prohibit...,"Does Chicago's Gang Congregation Ordinance, wh...","Yes. In a plurality ruling, Justice John Paul ...","<p dir=""ltr"">James Garcia Dimaya, a native and...",Is the Immigration and Nationality Act’s “crim...,The Immigration and Nationality Act’s “crime o...,keep_1,NaN,Both claims express the same core legal princi...
3,5876,5895,State legislative districts must have approxim...,State legislative districts must have nearly e...,0.992188,"WMCA, Inc. v. Lomenzo",Lucas v. Forty-Fourth General Assembly of Colo...,20,508,"```json\n{\n ""reasoning"": ""Both claims conv...",...,Both claims essentially articulate the same co...,"The WMCA, acting on behalf of several New York...",Did the apportionment formula contained in Art...,"Yes. In a 7-to-3 decision, the Court began by ...",Acting on behalf of several voters in the Denv...,Is a majority-approved state apportionment pla...,"Yes. In a 6-to-3 opinion, the Court held that ...",keep_1,NaN,Both claims convey the same core principle: st...
4,4655,4906,"If part of a law is found unconstitutional, th...","If part of a law is found unconstitutional, th...",0.988281,Free Enterprise Fund v. Public Company Oversig...,National Federation of Independent Business v....,08-861,11-393,"```json\n{\n ""reasoning"": ""Both claims expr...",...,Both claims articulate the same legal principl...,"The Free Enterprise Fund, a non-profit organiz...",1) Does the Sarbanes-Oxley Act violate the sep...,Yes. Yes. Not answered. The Supreme Court held...,"Amid intense public interest, Congress passed ...",Is the suit brought by respondents to challeng...,"No; Yes, under the Taxing and Spending Clause;...",keep_1,NaN,Both claims express the same legal principle –...

Contradiction Diff Case Head:

,index1,index2,claim1,claim2,score,name1,name2,docket1,docket2,llm_output,decision,explanation,facts1,api_question1,api_conclusion1,date1,facts2,api_question2,api_conclusion2,date2
0,2127,7197,States cannot be sued in federal court without...,States cannot be sued in another state's court...,0.949219,Seminole Tribe of Florida v. Florida,Franchise Tax Board of California v. Hyatt,94-12,17-1299,"```json\n{\n ""explanation"": ""Case 2 explici...",case2_overruled,Case 2 explicitly overrules *Nevada v. Hall* (...,The Seminole Tribe brought suit against the St...,Does the Eleventh Amendment provide Florida wi...,"Yes. In a 5-to-4 decision, The Court held that...",1995,"In 1993, a tax auditor for the Franchise Tax B...",Should the Court overrule its prior decision i...,"Nevada v. Hall, 440 US 410 (1979), is overrule...",2018
1,4383,4766,A lab report created for court use cannot be a...,Prosecutors cannot use a lab report in court u...,0.929688,Melendez-Diaz v. Massachusetts,Bullcoming v. New Mexico,07-591,09-10876,"```json\n{\n ""explanation"": ""Case 1 (Melend...",case1_overruled,"Case 1 (Melendez-Diaz v. Massachusetts, 2008) ...",Luis Melendez-Diaz was arrested while making a...,Is a state forensic analyst's laboratory repor...,Yes. The Supreme Court held that a state foren...,2008,Donald Bullcoming of New Mexico was sentenced ...,Can a blood-alcohol test admitted without the ...,Yes. The Supreme Court reversed and remanded t...,2010
2,2153,2652,Police can search a vehicle without a warrant ...,Police can search a car without a warrant even...,0.929688,Pennsylvania v. Labron,Maryland v. Dyson,95-1691,98-1062,"```json\n{\n ""explanation"": ""Case 1 (1995) ...",case1_overruled,Case 1 (1995) established that the automobile ...,This is the consolidation of two cases involvi...,"Does the Fourth Amendment, as applied to the S...","No. In a 7-2 per curiam opinion, the Court hel...",1995,Acting on a tip from a confidential informant ...,Does the Fourth Amendment require police to ob...,"No. In a per curiam opinion, the Court held th...",1998
3,2254,6819,Race cannot be the main factor when drawing di...,Race can be the main factor in drawing distric...,0.925781,Lawyer v. Department of Justice,Bethune-Hill v. Virginia Board of Elections,95-2024,15-680,"```json\n{\n ""explanation"": ""Case 2 (2016) ...",case1_overruled,Case 2 (2016) directly addresses and weakens t...,"Based on the 1990 census, the Florida Legislat...",Did the District Court err in approving a reme...,No. In a 5-4 opinion delivered by David H. Sou...,1996,"Based on the 2010 Census, the Virginia General...",Can race be a predominant consideration even w...,Race can still be shown to be the predominant ...,2016
4,820,1711,Police cannot search closed containers in a ve...,Police can search a container inside a car wit...,0.910156,Robbins v. California,California v. Acevedo,80-148,89-1690,"```json\n{\n ""explanation"": ""Case 1 (Robbin...",case1_overruled,"Case 1 (Robbins, 1980) established that the au...","During the early morning hours of January 5, 1...",May police officers search closed containers f...,No. Justice Potter Stewart delivered the opini...,1980,California police officers saw Charles Acevedo...,"Under the Fourth Amendment, may police conduct...",Yes. In a 6-3 decision authored by Justice Har...,1990

In [4]:
import pandas as pd

# Load the CSV files
metadata = pd.read_csv('../clean_data_with_details.csv')
# Print the head of both dataframes
print(metadata["disposition"].value_counts())

disposition
reversed/remanded            1073
affirmed                     1007
reversed                      585
vacated/remanded              430
reversed in-part/remanded      61
none                           41
reversed in-part               22
vacated                         7
vacated in-part/remanded        5
Name: count, dtype: int64

In [13]:
import pandas as pd

# Load the CSV files
filtered_claims_path = '../filtered_claims.csv'
metadata_path = '../clean_data_with_details.csv'

# Load dataframes
df_claims = pd.read_csv(filtered_claims_path)
df_meta = pd.read_csv(metadata_path)

# Normalize dispositions in metadata
def normalize_disp(d):
    return str(d).lower().strip()

df_meta['disposition_norm'] = df_meta['disposition'].apply(normalize_disp)

# Define allowed dispositions
allowed_dispositions = [
    'reversed/remanded', 
    'reversed', 
    'reversed in-part/remanded', 
    'reversed in-part'
]
allowed_dispositions = [normalize_disp(x) for x in allowed_dispositions]

# Identify the case name column in filtered_claims.csv
# It could be 'case_name' or 'name'
name_col = 'case_name'
if 'case_name' not in df_claims.columns and 'name' in df_claims.columns:
    name_col = 'name'

print(f"Using '{name_col}' column from filtered_claims.csv")

# Prepare for merge: normalize names
df_claims['name_clean'] = df_claims[name_col].astype(str).str.strip()
df_meta['name_clean'] = df_meta['name'].astype(str).str.strip()

# Merge claims with metadata to get disposition
merged_df = df_claims.merge(
    df_meta[['name_clean', 'disposition_norm']], 
    on='name_clean', 
    how='left'
)

# Calculate percentage
total_claims = len(merged_df)
valid_claims = merged_df[merged_df['disposition_norm'].isin(allowed_dispositions)]
num_valid = len(valid_claims)

percentage = (num_valid / total_claims) * 100 if total_claims > 0 else 0

print(f"Total Claims: {total_claims}")
print(f"Claims with Valid Disposition: {num_valid}")
print(f"Percentage: {percentage:.2f}%")

# Check for unmatched claims
unmatched = merged_df['disposition_norm'].isna().sum()
if unmatched > 0:
    print(f"Note: {unmatched} claims could not be matched to metadata (missing disposition).")

Using 'case_name' column from filtered_claims.csv
Total Claims: 7772
Claims with Valid Disposition: 4127
Percentage: 53.10%

In [5]:
import pandas as pd

# Load resolved contradictions
resolved_contra_path = '../results/factual_claims_resolved_contradictions.csv'
if pd.io.common.file_exists(resolved_contra_path):
    df_resolved = pd.read_csv(resolved_contra_path)

    # Load metadata for dispositions
    metadata_path = '../clean_data_with_details.csv'
    df_meta = pd.read_csv(metadata_path)

    # Helper to normalize dispositions
    def normalize_disp(d):
        return str(d).lower().strip()

    df_meta['disposition_norm'] = df_meta['disposition'].apply(normalize_disp)

    # Allowed dispositions for the *overruling* case (the one that wins)
    # If Case A overrules Case B, Case A must have one of these dispositions.
    allowed_dispositions = [
        'reversed/remanded', 
        'reversed', 
        'reversed in-part/remanded', 
        'reversed in-part'
    ]
    allowed_dispositions = [normalize_disp(x) for x in allowed_dispositions]

    # Merge dispositions
    # Case 1
    df_merged = df_resolved.merge(
        df_meta[['docket', 'name', 'disposition_norm']],
        left_on=['docket1', 'name1'],
        right_on=['docket', 'name'],
        how='left'
    )
    df_merged.rename(columns={'disposition_norm': 'disposition1'}, inplace=True)
    df_merged.drop(columns=['docket', 'name'], inplace=True)

    # Case 2
    df_merged = df_merged.merge(
        df_meta[['docket', 'name', 'disposition_norm']],
        left_on=['docket2', 'name2'],
        right_on=['docket', 'name'],
        how='left'
    )
    df_merged.rename(columns={'disposition_norm': 'disposition2'}, inplace=True)
    df_merged.drop(columns=['docket', 'name'], inplace=True)

    # Apply Logic
    def process_row(row):
        decision = str(row.get('decision', '')).strip()
        disp1 = row.get('disposition1', '')
        disp2 = row.get('disposition2', '')
        
        final_action = "keep_both" # Default (consistent or invalid overrule)
        
        if decision == 'case1_overruled':
            # Case 2 overrules Case 1. Case 2 must be a reversal.
            if disp2 in allowed_dispositions:
                final_action = "drop_claim1"
            else:
                final_action = "keep_both_invalid_disp"
                
        elif decision == 'case2_overruled':
            # Case 1 overrules Case 2. Case 1 must be a reversal.
            if disp1 in allowed_dispositions:
                final_action = "drop_claim2"
            else:
                final_action = "keep_both_invalid_disp"
                
        elif decision == 'consistent':
            final_action = "keep_both_consistent"
            
        return final_action

    df_merged['final_action'] = df_merged.apply(process_row, axis=1)

    # Stats
    print("Final Action Counts:")
    print(df_merged['final_action'].value_counts())

    print("\nDetails:")
    print(f"Total pairs: {len(df_merged)}")
    print(f"Valid Overrules (Drop 1): {len(df_merged[df_merged['final_action'] == 'drop_claim1'])}")
    print(f"Valid Overrules (Drop 2): {len(df_merged[df_merged['final_action'] == 'drop_claim2'])}")
    print(f"Invalid Overrules (Disposition mismatch): {len(df_merged[df_merged['final_action'] == 'keep_both_invalid_disp'])}")
    
    # Display some invalid overrules to check
    print("\n--- Examples of Invalid Overrules (Disposition Mismatch) ---")
    invalid_examples = df_merged[df_merged['final_action'] == 'keep_both_invalid_disp'].head(5)
    for i, row in invalid_examples.iterrows():
        print(f"Decision: {row['decision']}")
        print(f"Case 1 ({row['name1']}): {row['disposition1']}")
        print(f"Case 2 ({row['name2']}): {row['disposition2']}")
        print(f"Explanation: {row['explanation']}")
        print("-" * 20)

    # Save the results
    output_path = '../results/diff_case_removed_contra.csv'
    df_merged.to_csv(output_path, index=False)
    print(f"\nSaved results to {output_path}")
else:
    print(f"File not found: {resolved_contra_path}")

Final Action Counts:
final_action
keep_both_invalid_disp    882
drop_claim1               583
drop_claim2               476
keep_both_consistent        5
Name: count, dtype: int64

Details:
Total pairs: 1946
Valid Overrules (Drop 1): 583
Valid Overrules (Drop 2): 476
Invalid Overrules (Disposition mismatch): 882

--- Examples of Invalid Overrules (Disposition Mismatch) ---
Decision: case2_overruled
Case 1 (Seminole Tribe of Florida v. Florida): affirmed
Case 2 (Franchise Tax Board of California v. Hyatt): reversed/remanded
Explanation: Case 2 explicitly overrules *Nevada v. Hall* (1979), which had previously allowed states to be sued in other states' courts without consent. Case 1 discusses sovereign immunity in federal court, while Case 2 deals with sovereign immunity in *state* court. Case 2's ruling directly contradicts the principle established in *Nevada v. Hall* and thus effectively establishes that states *cannot* be sued in another state's court without their consent. This directly impacts the claim made in Case 1, as it extends the principle of sovereign immunity to inter-state lawsuits. Because Case 2 is a later ruling that overturns precedent, it overrules the implicit allowance of such suits that was present in the legal landscape before it.
--------------------
Decision: case1_overruled
Case 1 (Lawyer v. Department of Justice): affirmed
Case 2 (Bethune-Hill v. Virginia Board of Elections): vacated in-part/remanded
Explanation: Case 2 (2016) directly addresses and weakens the standard established in Case 1 (1996). Case 1 states that race did not *predominate* over traditional districting principles. Case 2 explicitly states that race *can* be the predominant factor even when traditional principles are respected, and that proving a conflict between race and those principles isn't required. The later ruling (Case 2) effectively overrules the stricter interpretation of equal protection in Case 1, allowing for greater consideration of race in redistricting. The ruling dates are also important; Case 2 is much more recent and represents a shift in the Court's thinking.
--------------------
Decision: case2_overruled
Case 1 (El Paso Natural Gas Company v. Neztsosie): vacated/remanded
Case 2 (Mims v. Arrow Financial Services, LLC): reversed/remanded
Explanation: Case 1 (1998) establishes that when a federal law like the Price-Anderson Act *explicitly* expresses a preference for a federal forum (and preempts tribal court jurisdiction in this instance), federal courts have the sole authority to determine jurisdiction. Case 2 (2011) establishes a presumption of *concurrent* jurisdiction between state and federal courts for federal laws, requiring an *explicit* statement of exclusive state jurisdiction to prevent federal court review. This is a direct contradiction. Case 2's ruling on the presumption of concurrent jurisdiction and the need for explicit exclusion of federal jurisdiction effectively overrules the narrower, more forceful assertion of federal jurisdiction in Case 1. The later case sets a higher bar for exclusive federal jurisdiction, meaning the reasoning in Case 1 is no longer controlling law.
--------------------
Decision: case1_overruled
Case 1 (Hughes v. United States): reversed/remanded
Case 2 (Koons v. United States): affirmed
Explanation: Case 2, decided in 2017, directly contradicts the core holding of Case 1, also decided in 2017. Case 1 establishes that a sentence is 'based on' the guidelines range if it was *a* component of the court's reasoning, even with a plea bargain. Case 2, however, states that a sentence is *not* 'based on' the guidelines range if it was primarily based on a mandatory minimum and substantial assistance, even if the guidelines range existed as a backdrop. Because Case 2 explicitly limits the scope of what constitutes a sentence 'based on' the guidelines, it effectively overrules the broader interpretation presented in Case 1. The later case clarifies and narrows the application of the statute, negating the effect of the earlier case's broader holding. While both cases were decided in the same year, Case 2's interpretation is more restrictive and therefore supersedes Case 1's.
--------------------
Decision: case1_overruled
Case 1 (Thornton v. United States): affirmed
Case 2 (Arizona v. Gant): affirmed
Explanation: Case 1 (Thornton, 2003) established a broader allowance for searching a vehicle incident to arrest, even after the suspect has exited, prioritizing officer safety and evidence preservation. Case 2 (Gant, 2008) narrowed this allowance, requiring a reasonable belief that the arrestee could access the vehicle or that evidence related to the *arresting offense* was within the vehicle.  Because Gant was decided five years *after* Thornton, and specifically limited the scope of the search incident to arrest exception established in Thornton, it effectively overruled Thornton. The Gant ruling explicitly states the need for a link between the search and the reason for the arrest, a condition not present in Thornton. The dissent in Gant specifically points to Thornton as a precedent being overruled.
--------------------

Saved results to ../results/diff_case_removed_contra.csv

In [6]:
import pandas as pd
import os

# Load resolved overlaps
resolved_overlap_path = '../results/factual_claims_resolved_overlaps.csv'

if os.path.exists(resolved_overlap_path):
    df_overlaps = pd.read_csv(resolved_overlap_path)
    
    # Apply Logic
    def process_overlap_row(row):
        decision = str(row.get('resolution_decision', '')).strip()
        
        final_action = "keep_both" # Default
        
        if decision == 'keep_1':
            final_action = "drop_claim2"
        elif decision == 'keep_2':
            final_action = "drop_claim1"
        elif decision == 'merge':
            final_action = "merge_claims"
            
        return final_action

    df_overlaps['final_action'] = df_overlaps.apply(process_overlap_row, axis=1)

    # Stats
    print("Final Action Counts:")
    print(df_overlaps['final_action'].value_counts())

    print("\nDetails:")
    print(f"Total pairs: {len(df_overlaps)}")
    print(f"Keep Claim 1 (Drop 2): {len(df_overlaps[df_overlaps['final_action'] == 'drop_claim2'])}")
    print(f"Keep Claim 2 (Drop 1): {len(df_overlaps[df_overlaps['final_action'] == 'drop_claim1'])}")
    print(f"Merge Claims: {len(df_overlaps[df_overlaps['final_action'] == 'merge_claims'])}")
    
    # Save the results
    output_path = '../results/diff_case_removed_overlaps.csv'
    df_overlaps.to_csv(output_path, index=False)
    print(f"\nSaved results to {output_path}")
else:
    print(f"File not found: {resolved_overlap_path}")

Final Action Counts:
final_action
drop_claim2     1812
drop_claim1      141
merge_claims       2
Name: count, dtype: int64

Details:
Total pairs: 1955
Keep Claim 1 (Drop 2): 1812
Keep Claim 2 (Drop 1): 141
Merge Claims: 2

Saved results to ../results/diff_case_removed_overlaps.csv

In [5]:
import pandas as pd
import networkx as nx
import json
import os

# 1. Load Data
overlaps_path = '../results/factual_claims_resolved_overlaps_diff_case.csv'
contradictions_path = '../results/factual_claims_resolved_contradictions_diff_case.csv'
filtered_claims_path = '../filtered_claims.csv'
metadata_path = '../clean_data_with_details.csv'

# Check if filtered_claims exists, else try factual_claims
if not os.path.exists(filtered_claims_path):
    print(f"{filtered_claims_path} not found, trying ../factual_claims.csv")
    filtered_claims_path = '../factual_claims.csv'

df_overlaps = pd.read_csv(overlaps_path)
df_contradictions = pd.read_csv(contradictions_path)
df_claims = pd.read_csv(filtered_claims_path)
df_meta = pd.read_csv(metadata_path)

print(f"Loaded {len(df_claims)} filtered claims.")
print(f"Loaded {len(df_overlaps)} overlap pairs.")
print(f"Loaded {len(df_contradictions)} contradiction pairs.")

# Normalize dispositions for checking
def normalize_disp(d):
    return str(d).lower().strip()

df_meta['disposition_norm'] = df_meta['disposition'].apply(normalize_disp)
disposition_map = dict(zip(df_meta['name'], df_meta['disposition_norm']))

allowed_dispositions = [
    'reversed/remanded', 
    'reversed', 
    'reversed in-part/remanded', 
    'reversed in-part'
]
allowed_dispositions = [normalize_disp(x) for x in allowed_dispositions]

# Create lookup for claims
# Assuming (name, claim) is unique. 
df_claims['claim_clean'] = df_claims['claim'].astype(str).str.strip()

# Identify the name column (could be 'name' or 'case_name')
name_col = 'name'
if 'case_name' in df_claims.columns:
    name_col = 'case_name'
elif 'name' not in df_claims.columns:
    print("Warning: Neither 'name' nor 'case_name' found in claims file. Using first column?")
    name_col = df_claims.columns[0]

print(f"Using '{name_col}' as the case name column.")
df_claims['name_clean'] = df_claims[name_col].astype(str).str.strip()
df_claims['id'] = df_claims.index

# Map (name, claim) -> ID
claim_lookup = {}
for idx, row in df_claims.iterrows():
    claim_lookup[(row['name_clean'], row['claim_clean'])] = idx

def get_claim_id(name, claim):
    return claim_lookup.get((str(name).strip(), str(claim).strip()))

print("Lookup map created.")

Loaded 7583 filtered claims.
Loaded 1955 overlap pairs.
Loaded 1946 contradiction pairs.
Using 'case_name' as the case name column.
Lookup map created.

In [6]:
# 2. Process Overlaps (Merge Conflicts)
G_overlap = nx.Graph()
G_overlap.add_nodes_from(df_claims['id'])

overlap_conflicts = 0
for _, row in df_overlaps.iterrows():
    id1 = get_claim_id(row['name1'], row['claim1'])
    id2 = get_claim_id(row['name2'], row['claim2'])
    
    if id1 is not None and id2 is not None:
        decision = str(row.get('resolution_decision', '')).strip()
        if decision in ['keep_1', 'keep_2', 'merge']:
            G_overlap.add_edge(id1, id2, decision=decision, merged_claim=row.get('merged_claim'))
            
            if G_overlap.degree[id1] > 1 or G_overlap.degree[id2] > 1:
                overlap_conflicts += 1

print(f"Overlap Merge Conflicts (nodes involved in multiple pairs): {overlap_conflicts}")

# Find components
raw_components = list(nx.connected_components(G_overlap))
print(f"Found {len(raw_components)} raw components (including singletons).")

# Refine components (Split large ones > 5)
components = []
for comp in raw_components:
    if len(comp) <= 5:
        components.append(comp)
    else:
        # Split large component: Merge along sub-branches with different cases
        # Strategy: Greedy clustering ensuring unique cases in each cluster
        subgraph = G_overlap.subgraph(comp)
        remaining_nodes = set(comp)
        
        while remaining_nodes:
            # Pick a start node
            start_node = next(iter(remaining_nodes))
            remaining_nodes.remove(start_node)
            
            cluster = {start_node}
            # Track cases in this cluster to ensure uniqueness
            cluster_cases = {df_claims.loc[start_node, name_col]}
            
            # BFS/Traversal to grow cluster
            queue = [start_node]
            
            while queue:
                u = queue.pop(0)
                for v in subgraph.neighbors(u):
                    if v in remaining_nodes:
                        v_case = df_claims.loc[v, name_col]
                        # Only merge if the case is not already in the cluster
                        if v_case not in cluster_cases:
                            cluster.add(v)
                            cluster_cases.add(v_case)
                            remaining_nodes.remove(v)
                            queue.append(v)
            
            components.append(cluster)

print(f"Refined to {len(components)} components after splitting large ones (>5).")

multi_node_components = [c for c in components if len(c) > 1]
print(f"Found {len(multi_node_components)} multi-claim components to merge.")

# Example of merge conflict
print("\n--- Examples of Merges ---")
count = 0
for c in multi_node_components:
    if len(c) > 2:
        print(f"Complex Merge (Size {len(c)}): Merging cases for these claims:")
        # Print names
        for node_id in list(c):
            print(f" - Case: {df_claims.loc[node_id, name_col]} | Claim: {df_claims.loc[node_id, 'claim'][:50]}...")
        print("-" * 20)
        count += 1
        if count >= 3: break

if count == 0 and len(multi_node_components) > 0:
    print("No complex merges (>2) found. Showing simple merge:")
    c = multi_node_components[0]
    for node_id in list(c):
        print(f" - Case: {df_claims.loc[node_id, name_col]} | Claim: {df_claims.loc[node_id, 'claim'][:50]}...")

Overlap Merge Conflicts (nodes involved in multiple pairs): 1466
Found 6340 raw components (including singletons).
Refined to 6496 components after splitting large ones (>5).
Found 412 multi-claim components to merge.

--- Examples of Merges ---
Complex Merge (Size 23): Merging cases for these claims:
 - Case: United States Department of Agriculture v. Moreno | Claim: Laws that treat people differently must have a rea...
 - Case: Exxon Corporation v. Governor of Maryland | Claim: Courts cannot strike down a law just because they ...
 - Case: Kadrmas v. Dickinson Public Schools | Claim: A government policy that treats different groups d...
 - Case: Village of Willowbrook v. Olechon | Claim: The government cannot treat people differently wit...
 - Case: Reed v. Reed | Claim: Government rules that treat men and women differen...
 - Case: Armour v. City of Indianapolis | Claim: Governments can treat people differently under the...
 - Case: Weinberger v. Wiesenfeld | Claim: The federal government cannot give different benef...
 - Case: Vance v. Bradley | Claim: Federal laws that treat different groups of worker...
 - Case: Central State Univ. v. American Assn. of Univ. Professors, Central State Univ. Chapter | Claim: Laws that treat different groups of public employe...
 - Case: United States v. Virginia | Claim: Government actions that treat people differently b...
 - Case: Exxon Corporation v. Eagerton | Claim: Laws that treat different groups differently are a...
 - Case: Kahn v. Shevin | Claim: When a law uses gender to decide who gets benefits...
 - Case: United States Railroad Retirement Board v. Fritz | Claim: The Constitution does not require laws to be perfe...
 - Case: General Motors Corporation v. Tracy | Claim: The Equal Protection Clause allows states to apply...
 - Case: Sessions v. Morales-Santana | Claim: The government can't make laws that treat men and ...
 - Case: Mississippi University for Women v. Hogan | Claim: Laws that assume certain jobs are only for men or ...
 - Case: Tuan Anh Nguyen v. Immigration and Naturalization Service | Claim: Laws that treat men and women differently must be ...
 - Case: Califano v. Goldfarb | Claim: Survivor benefit rules must be the same for both g...
 - Case: Heller  v. Doe | Claim: Laws that treat people differently must have a rea...
 - Case: Craig v. Boren | Claim: Laws that treat men and women differently must be ...
 - Case: Frontiero v. Richardson | Claim: Gender-based differences in government rules must ...
 - Case: Orr v. Orr | Claim: Laws that treat men and women differently must hav...
 - Case: Federal Communications Commission v. Beach Communications, Inc. | Claim: Courts will keep a law in place if there's a plaus...
--------------------
Complex Merge (Size 6): Merging cases for these claims:
 - Case: Sable Communications of California v. Federal Communications Commission | Claim: Obscene speech is not protected by the First Amend...
 - Case: Redrup v. New York | Claim: Some judges believe the government cannot ban any ...
 - Case: Paris Adult Theatre I v. Slaton | Claim: Governments can ban obscene materials to protect c...
 - Case: Miller v. California | Claim: The First Amendment does not protect the sale or d...
 - Case: Kingsley Books, Inc. v. Brown | Claim: Obscene materials are not protected by the First A...
 - Case: Roth v. United States | Claim: The First Amendment does not protect obscene mater...
--------------------
Complex Merge (Size 3): Merging cases for these claims:
 - Case: Brown v. United States | Claim: If a law provides immunity from prosecution for te...
 - Case: Kastigar v. United States | Claim: The Fifth Amendment right to stay silent does not ...
 - Case: Sarno v. Illinois Crime Investigating Commission | Claim: A witness cannot refuse to testify under the Fifth...
--------------------

In [7]:
# 3. Process Contradictions
# Filter valid contradictions based on disposition
valid_contradictions = []

for _, row in df_contradictions.iterrows():
    id1 = get_claim_id(row['name1'], row['claim1'])
    id2 = get_claim_id(row['name2'], row['claim2'])
    
    if id1 is not None and id2 is not None:
        decision = str(row.get('decision', '')).strip()
        disp1 = disposition_map.get(str(row['name1']).strip(), '')
        disp2 = disposition_map.get(str(row['name2']).strip(), '')
        
        winner = None
        loser = None
        
        if decision == 'case1_overruled':
            # Case 2 overrules Case 1. Case 2 must be reversal.
            if disp2 in allowed_dispositions:
                winner = id2
                loser = id1
        elif decision == 'case2_overruled':
            # Case 1 overrules Case 2. Case 1 must be reversal.
            if disp1 in allowed_dispositions:
                winner = id1
                loser = id2
        
        if winner is not None:
            valid_contradictions.append({
                'winner': winner,
                'loser': loser,
                'winner_name': row['name2'] if winner == id2 else row['name1'],
                'loser_name': row['name1'] if winner == id2 else row['name2']
            })

print(f"Found {len(valid_contradictions)} valid overruling pairs.")

# Check for multiple overrulings (A overruled by B, A overruled by C)
loser_counts = {}
for item in valid_contradictions:
    l = item['loser']
    loser_counts[l] = loser_counts.get(l, 0) + 1

multi_overruled = {k: v for k, v in loser_counts.items() if v > 1}
print(f"Claims overruled multiple times (by different cases): {len(multi_overruled)}")
if len(multi_overruled) > 0:
    print("Example IDs of multi-overruled claims:", list(multi_overruled.keys())[:5])
    # Print details for one
    example_id = list(multi_overruled.keys())[0]
    print(f"Example Claim ID {example_id} overruled by:")
    for item in valid_contradictions:
        if item['loser'] == example_id:
            print(f" - {item['winner_name']}")

# Check for serial overrulings (A overrules B, B overrules C)
winners = set(item['winner'] for item in valid_contradictions)
losers = set(item['loser'] for item in valid_contradictions)
serial = winners.intersection(losers)
print(f"Serial Overrulings (A->B->C): {len(serial)}")
if len(serial) > 0:
    print("Example IDs in middle of chain:", list(serial)[:5])

Found 1059 valid overruling pairs.
Claims overruled multiple times (by different cases): 191
Example IDs of multi-overruled claims: [820, 284, 6819, 724, 4984]
Example Claim ID 820 overruled by:
 - California v. Acevedo
 - Wyoming v. Houghton
 - Florida v. Jimeno
 - New York v. Belton
 - New York v. Belton
Serial Overrulings (A->B->C): 151
Example IDs in middle of chain: [3593, 7178, 19, 4116, 4117]

In [8]:
# 4. Apply Updates and Create Final DataFrame

# Map original ID -> Super Claim ID (Leader of component)
id_map = {}
component_data = {} # leader_id -> {ids: [], text: ..., cases: []}

for comp in components:
    comp_list = list(comp)
    leader = comp_list[0] # Pick first as leader
    
    # Determine text
    # If any merge decision in component, try to find merged text
    final_text = df_claims.loc[leader, 'claim']
    
    # Check edges for merged text
    subgraph = G_overlap.subgraph(comp)
    for u, v, data in subgraph.edges(data=True):
        if data.get('decision') == 'merge':
            mc = data.get('merged_claim')
            if mc and isinstance(mc, str) and len(mc) > 10:
                final_text = mc
                break
    
    # Collect cases from ALL nodes in the component
    cases = []
    for node in comp:
        id_map[node] = leader
        # Use the identified name column
        cases.append(df_claims.loc[node, name_col])
    
    component_data[leader] = {
        'ids': comp_list,
        'text': final_text,
        'cases': sorted(list(set(cases))), # Unique cases
        'type': 'confirmed' if len(comp) > 1 else 'none',
        'overruling_case': None
    }

# Apply Contradictions
claims_to_drop = set()

for item in valid_contradictions:
    # Find the leader for the winner and loser (in case they were part of overlaps)
    # Note: id_map contains all nodes because components include singletons
    winner_leader = id_map[item['winner']]
    loser_leader = id_map[item['loser']]
    
    if winner_leader == loser_leader:
        # Contradiction within the same merged component? Should be rare/impossible if logic holds.
        continue
        
    # Update Winner
    winner_data = component_data[winner_leader]
    loser_data = component_data[loser_leader]
    
    # Merge cases (Winner takes Loser's cases into its history)
    winner_data['cases'].extend(loser_data['cases'])
    winner_data['cases'] = sorted(list(set(winner_data['cases'])))
    
    # Update type and overruling info
    winner_data['type'] = 'overruling'
    # If already overruled, maybe append? For now, just take the last one or keep list.
    # User asked for "overruling_case" column.
    if winner_data['overruling_case'] is None:
        winner_data['overruling_case'] = item['winner_name']
    else:
        # If multiple overrulers, maybe list them?
        if item['winner_name'] not in winner_data['overruling_case']:
             winner_data['overruling_case'] += f"; {item['winner_name']}"
    
    # Mark loser for drop
    claims_to_drop.add(loser_leader)

# Construct Final DataFrame
final_rows = []
for leader, data in component_data.items():
    if leader in claims_to_drop:
        continue
        
    # Get original row data
    row = df_claims.loc[leader].copy()
    
    # Update fields
    row['claim'] = data['text']
    row['case_name'] = json.dumps(data['cases']) # JSON structure
    row['type'] = data['type']
    row['overruling_case'] = data['overruling_case']
    
    # Remove helper cols
    if 'claim_clean' in row: del row['claim_clean']
    if 'name_clean' in row: del row['name_clean']
    if 'id' in row: del row['id']
    # Remove original 'name' if we are using 'case_name'
    if 'name' in row: del row['name']
    
    final_rows.append(row)

df_final = pd.DataFrame(final_rows)

# Ensure 'claim' is first
cols = ['claim'] + [c for c in df_final.columns if c != 'claim']
df_final = df_final[cols]

print(f"Final DataFrame Size: {len(df_final)}")
print(df_final['type'].value_counts())

# Save
output_path = '../diff_case_claims_updated.csv'
df_final.to_csv(output_path, index=False)
print(f"Saved to {output_path}")

Final DataFrame Size: 5910
type
none          5347
overruling     343
confirmed      220
Name: count, dtype: int64
Saved to ../diff_case_claims_updated.csv

In [9]:
import pandas as pd
import json
import os

output_path = '../diff_case_claims_updated.csv'

if os.path.exists(output_path):
    df_final = pd.read_csv(output_path)
    print(f"Loaded {len(df_final)} rows.")
    
    # Check for duplicates
    dup_count = df_final.duplicated(subset=['claim']).sum()
    print(f"Duplicate claims found: {dup_count}")
    
    if dup_count > 0:
        print("Merging duplicates...")
        rows = []
        for claim, group in df_final.groupby('claim'):
            if len(group) == 1:
                rows.append(group.iloc[0])
            else:
                # Base row
                row = group.iloc[0].copy()
                
                # Merge cases
                all_cases = set()
                for c_json in group['case_name']:
                    try:
                        cases = json.loads(c_json)
                        if isinstance(cases, list):
                            all_cases.update(cases)
                    except:
                        pass
                row['case_name'] = json.dumps(sorted(list(all_cases)))
                
                # Merge type
                types = set(group['type'])
                if 'overruling' in types:
                    row['type'] = 'overruling'
                elif 'confirmed' in types:
                    row['type'] = 'confirmed'
                
                # Merge overruling cases
                ocs = set()
                for oc in group['overruling_case'].dropna():
                    ocs.add(oc)
                if ocs:
                    row['overruling_case'] = "; ".join(sorted(list(ocs)))
                
                rows.append(row)
        
        df_final = pd.DataFrame(rows)
        print(f"New size: {len(df_final)}")
        df_final.to_csv(output_path, index=False)
    
    print("\nHead of Final Dataset:")
    display(df_final.head())
    
    print("\nType Distribution:")
    print(df_final['type'].value_counts())

else:
    print("File not found.")

Loaded 5910 rows.
Duplicate claims found: 0

Head of Final Dataset:

,claim,case_name,judgement,explanation,raw_output,type,overruling_case
0,The Constitution protects a person's right to ...,"[""Roe v. Wade""]",consistent,The case evidence explicitly states that the C...,"```json\n{\n ""explanation"": ""The case evide...",none,NaN
1,States cannot restrict abortion during the fir...,"[""Roe v. Wade""]",consistent,"The case evidence explicitly states that ""In t...","```json\n{\n ""explanation"": ""The case evide...",none,NaN
2,"During the second three months of pregnancy, s...","[""Roe v. Wade""]",consistent,The case evidence states that in the second tr...,"```json\n{\n ""explanation"": ""The case evide...",none,NaN
3,"After the fetus can survive outside the womb, ...","[""Roe v. Wade""]",consistent,The case evidence states that in the third tri...,"```json\n{\n ""explanation"": ""The case evide...",none,NaN
4,States cannot take children from unwed fathers...,"[""Stanley v. Illinois""]",consistent,The case evidence states that the Supreme Cour...,"```json\n{\n ""explanation"": ""The case evide...",none,NaN

Type Distribution:
type
none          5347
overruling     343
confirmed      220
Name: count, dtype: int64

In [12]:
import pandas as pd
import os

# Path to the updated claims file
file_path = '../diff_case_claims_updated.csv'

if os.path.exists(file_path):
    df = pd.read_csv(file_path)
    
    # Add fact_id if it doesn't exist
    if 'fact_id' not in df.columns:
        print("Adding fact_id column...")
        df['fact_id'] = range(len(df))
        
        # Save back
        df.to_csv(file_path, index=False)
        print(f"Saved updated file with {len(df)} rows and columns: {df.columns.tolist()}")
    else:
        print("fact_id already exists.")
        print(df.head())
else:
    print(f"File not found: {file_path}")

Adding fact_id column...
Saved updated file with 5910 rows and columns: ['claim', 'case_name', 'judgement', 'explanation', 'raw_output', 'type', 'overruling_case', 'fact_id']

In [ ]:
import pandas as pd
import networkx as nx
import json
import os

# 1. Load Data
overlaps_path = '../results/factual_claims_resolved_overlaps_diff_case.csv'
contradictions_path = '../results/factual_claims_resolved_contradictions_diff_case.csv'
filtered_claims_path = '../filtered_claims.csv'
metadata_path = '../clean_data_with_details.csv'

# Check if filtered_claims exists, else try factual_claims
if not os.path.exists(filtered_claims_path):
    print(f"{filtered_claims_path} not found, trying ../factual_claims.csv")
    filtered_claims_path = '../factual_claims.csv'

df_overlaps = pd.read_csv(overlaps_path)
df_contradictions = pd.read_csv(contradictions_path)
df_claims = pd.read_csv(filtered_claims_path)
df_meta = pd.read_csv(metadata_path)

print(f"Loaded {len(df_claims)} filtered claims.")
print(f"Loaded {len(df_overlaps)} overlap pairs.")
print(f"Loaded {len(df_contradictions)} contradiction pairs.")

# Normalize dispositions for checking
def normalize_disp(d):
    return str(d).lower().strip()

df_meta['disposition_norm'] = df_meta['disposition'].apply(normalize_disp)
disposition_map = dict(zip(df_meta['name'], df_meta['disposition_norm']))

allowed_dispositions = [
    'reversed/remanded', 
    'reversed', 
    'reversed in-part/remanded', 
    'reversed in-part'
]
allowed_dispositions = [normalize_disp(x) for x in allowed_dispositions]

# Create lookup for claims
df_claims['claim_clean'] = df_claims['claim'].astype(str).str.strip()

# Identify the name column
name_col = 'name'
if 'case_name' in df_claims.columns:
    name_col = 'case_name'
elif 'name' not in df_claims.columns:
    name_col = df_claims.columns[0]

print(f"Using '{name_col}' as the case name column.")
df_claims['name_clean'] = df_claims[name_col].astype(str).str.strip()
df_claims['id'] = df_claims.index

# Map (name, claim) -> ID
claim_lookup = {}
for idx, row in df_claims.iterrows():
    claim_lookup[(row['name_clean'], row['claim_clean'])] = idx

def get_claim_id(name, claim):
    return claim_lookup.get((str(name).strip(), str(claim).strip()))

# 2. Process Overlaps (Merge Conflicts) - Reusing logic to build components
G_overlap = nx.Graph()
G_overlap.add_nodes_from(df_claims['id'])

for _, row in df_overlaps.iterrows():
    id1 = get_claim_id(row['name1'], row['claim1'])
    id2 = get_claim_id(row['name2'], row['claim2'])
    
    if id1 is not None and id2 is not None:
        decision = str(row.get('resolution_decision', '')).strip()
        if decision in ['keep_1', 'keep_2', 'merge']:
            G_overlap.add_edge(id1, id2, decision=decision, merged_claim=row.get('merged_claim'))

# Find components
raw_components = list(nx.connected_components(G_overlap))

# Refine components (Split large ones > 5)
components = []
for comp in raw_components:
    if len(comp) <= 5:
        components.append(comp)
    else:
        subgraph = G_overlap.subgraph(comp)
        remaining_nodes = set(comp)
        
        while remaining_nodes:
            start_node = next(iter(remaining_nodes))
            remaining_nodes.remove(start_node)
            
            cluster = {start_node}
            cluster_cases = {df_claims.loc[start_node, name_col]}
            
            queue = [start_node]
            
            while queue:
                u = queue.pop(0)
                for v in subgraph.neighbors(u):
                    if v in remaining_nodes:
                        v_case = df_claims.loc[v, name_col]
                        if v_case not in cluster_cases:
                            cluster.add(v)
                            cluster_cases.add(v_case)
                            remaining_nodes.remove(v)
                            queue.append(v)
            
            components.append(cluster)

print(f"Refined to {len(components)} components.")

# 3. Initialize Component Data
id_map = {}
component_data = {} # leader_id -> {ids: [], text: ..., cases: []}

for comp in components:
    comp_list = list(comp)
    leader = comp_list[0]
    
    final_text = df_claims.loc[leader, 'claim']
    
    subgraph = G_overlap.subgraph(comp)
    for u, v, data in subgraph.edges(data=True):
        if data.get('decision') == 'merge':
            mc = data.get('merged_claim')
            if mc and isinstance(mc, str) and len(mc) > 10:
                final_text = mc
                break
    
    cases = []
    for node in comp:
        id_map[node] = leader
        cases.append(df_claims.loc[node, name_col])
    
    component_data[leader] = {
        'ids': comp_list,
        'text': final_text,
        'cases': sorted(list(set(cases))),
        'type': 'confirmed' if len(comp) > 1 else 'none',
        'overruling_case': None
    }

# 4. Process Contradictions (UPDATED LOGIC)
valid_contradictions = []

for _, row in df_contradictions.iterrows():
    id1 = get_claim_id(row['name1'], row['claim1'])
    id2 = get_claim_id(row['name2'], row['claim2'])
    
    if id1 is not None and id2 is not None:
        decision = str(row.get('decision', '')).strip()
        disp1 = disposition_map.get(str(row['name1']).strip(), '')
        disp2 = disposition_map.get(str(row['name2']).strip(), '')
        
        winner = None
        loser = None
        
        if decision == 'case1_overruled':
            if disp2 in allowed_dispositions:
                winner = id2
                loser = id1
        elif decision == 'case2_overruled':
            if disp1 in allowed_dispositions:
                winner = id1
                loser = id2
        
        if winner is not None:
            # Find leaders
            winner_leader = id_map[winner]
            loser_leader = id_map[loser]
            
            if winner_leader != loser_leader:
                winner_name = row['name2'] if winner == id2 else row['name1']
                
                # Update Loser (The overruled claim)
                loser_data = component_data[loser_leader]
                loser_data['type'] = 'overruled'
                
                if loser_data['overruling_case'] is None:
                    loser_data['overruling_case'] = winner_name
                else:
                    if winner_name not in loser_data['overruling_case']:
                         loser_data['overruling_case'] += f"; {winner_name}"

# 5. Construct Final DataFrame
final_rows = []
for leader, data in component_data.items():
    # We keep ALL claims now (no claims_to_drop)
    
    row = df_claims.loc[leader].copy()
    
    row['claim'] = data['text']
    row['case_name'] = json.dumps(data['cases'])
    row['type'] = data['type']
    row['overruling_case'] = data['overruling_case']
    
    if 'claim_clean' in row: del row['claim_clean']
    if 'name_clean' in row: del row['name_clean']
    if 'id' in row: del row['id']
    if 'name' in row: del row['name']
    
    final_rows.append(row)

df_final = pd.DataFrame(final_rows)

# Ensure 'claim' is first
cols = ['claim'] + [c for c in df_final.columns if c != 'claim']
df_final = df_final[cols]

print(f"Final DataFrame Size: {len(df_final)}")
print(df_final['type'].value_counts())

# Save
output_path = '../diff_case_claims_updated.csv'
df_final.to_csv(output_path, index=False)
print(f"Saved to {output_path}")

In [1]:
import pandas as pd
import json
import os
import numpy as np

# 1. Load Data
current_file_path = '../diff_case_claims_with_negatives.csv'
contradictions_path = '../results/factual_claims_resolved_contradictions_diff_case.csv'
metadata_path = '../clean_data_with_details.csv'

print("Loading files...")
df_current = pd.read_csv(current_file_path)
df_contradictions = pd.read_csv(contradictions_path)
df_meta = pd.read_csv(metadata_path)

print(f"Current dataset shape: {df_current.shape}")
print(f"Contradictions shape: {df_contradictions.shape}")

# 2. Setup Disposition Logic (to identify Winner/Loser correctly)
def normalize_disp(d):
    return str(d).lower().strip()

df_meta['disposition_norm'] = df_meta['disposition'].apply(normalize_disp)
disposition_map = dict(zip(df_meta['name'], df_meta['disposition_norm']))

allowed_dispositions = [
    'reversed/remanded', 
    'reversed', 
    'reversed in-part/remanded', 
    'reversed in-part'
]
allowed_dispositions = [normalize_disp(x) for x in allowed_dispositions]

# 3. Identify Valid Contradictions and Losers
# We need to find the losers that correspond to the winners present in df_current.

# First, identify all valid (Winner, Loser, Loser_Claim) tuples from contradictions
valid_contradictions = []

for _, row in df_contradictions.iterrows():
    decision = str(row.get('decision', '')).strip()
    disp1 = disposition_map.get(str(row['name1']).strip(), '')
    disp2 = disposition_map.get(str(row['name2']).strip(), '')
    
    winner_name = None
    loser_name = None
    loser_claim = None
    
    if decision == 'case1_overruled':
        # Case 2 overrules Case 1. Case 2 must be reversal.
        if disp2 in allowed_dispositions:
            winner_name = row['name2']
            loser_name = row['name1']
            loser_claim = row['claim1']
    elif decision == 'case2_overruled':
        # Case 1 overrules Case 2. Case 1 must be reversal.
        if disp1 in allowed_dispositions:
            winner_name = row['name1']
            loser_name = row['name2']
            loser_claim = row['claim2']
    
    if winner_name and loser_name:
        valid_contradictions.append({
            'winner': winner_name,
            'loser': loser_name,
            'loser_claim': loser_claim
        })

print(f"Found {len(valid_contradictions)} valid contradiction pairs in source data.")

# 4. Identify Winners present in the current dataset
# The 'overruling_case' column in df_current (for type='overruling') contains the Winner's name.
overruling_rows_mask = df_current['type'] == 'overruling'
overruling_rows = df_current[overruling_rows_mask]

print(f"Found {len(overruling_rows)} rows with type='overruling' in current dataset.")

# Extract all winner names referenced in the dataset
# The 'overruling_case' column might contain multiple names separated by "; "
present_winners = set()
for val in overruling_rows['overruling_case'].dropna():
    names = [n.strip() for n in str(val).split(';')]
    present_winners.update(names)

print(f"Identified {len(present_winners)} unique winner cases referenced in dataset.")

# 5. Filter Contradictions to find relevant Losers
# We only care about losers overruled by the winners we found
relevant_losers = []
for item in valid_contradictions:
    if item['winner'] in present_winners:
        relevant_losers.append(item)

print(f"Found {len(relevant_losers)} relevant dropped claims (losers) to restore.")

# 6. Create Rows for Dropped Claims
# Group by (loser_name, loser_claim) to handle multiple overrulers
loser_map = {} # (name, claim) -> set of winners

for item in relevant_losers:
    key = (item['loser'], item['loser_claim'])
    if key not in loser_map:
        loser_map[key] = set()
    loser_map[key].add(item['winner'])

new_rows = []
next_fact_id = df_current['fact_id'].max() + 1 if 'fact_id' in df_current.columns else 0

for (l_name, l_claim), winners in loser_map.items():
    # Create new row
    new_row = {
        'claim': l_claim,
        'case_name': json.dumps([l_name]),
        'judgement': np.nan, # Missing
        'explanation': np.nan, # Missing
        'raw_output': np.nan, # Missing
        'type': 'overruled',
        'overruling_case': "; ".join(sorted(list(winners))),
        'fact_id': next_fact_id,
        'label': 1, # Assuming positive sample
        'is_negation': False
    }
    new_rows.append(new_row)
    next_fact_id += 1

print(f"Created {len(new_rows)} new rows for overruled claims.")

# 7. Update Current Dataset
# Change type 'overruling' -> 'none' and clear 'overruling_case'
# Note: We do this for ALL 'overruling' rows, as they are now just normal claims (winners)
df_current.loc[overruling_rows_mask, 'type'] = 'none'
df_current.loc[overruling_rows_mask, 'overruling_case'] = np.nan

# 8. Append New Rows
if new_rows:
    df_new = pd.DataFrame(new_rows)
    df_final = pd.concat([df_current, df_new], ignore_index=True)
else:
    df_final = df_current

print(f"Final dataset shape: {df_final.shape}")
print("Type distribution:")
print(df_final['type'].value_counts())

# 9. Save
output_path = '../diff_case_claims_with_negatives_fixed.csv'
df_final.to_csv(output_path, index=False)
print(f"Saved fixed dataset to {output_path}")

# Optional: Overwrite original if desired, but saving to new file first for safety
# df_final.to_csv(current_file_path, index=False)

Loading files...
Current dataset shape: (11818, 10)
Contradictions shape: (1946, 20)
Found 1059 valid contradiction pairs in source data.
Found 686 rows with type='overruling' in current dataset.
Identified 302 unique winner cases referenced in dataset.
Found 697 relevant dropped claims (losers) to restore.
Created 492 new rows for overruled claims.
Final dataset shape: (12310, 10)
Type distribution:
type
none         11378
overruled      492
confirmed      440
Name: count, dtype: int64
Saved fixed dataset to ../diff_case_claims_with_negatives_fixed.csv

In [2]:
import pandas as pd
import os

# Load the fixed dataset
file_path = '../diff_case_claims_with_negatives_fixed.csv'

if os.path.exists(file_path):
    df = pd.read_csv(file_path)
    
    # 1. Drop invalid negations (overruled + is_negation=True)
    # These shouldn't exist based on our logic, but good to filter
    mask_drop = (df['type'] == 'overruled') & (df['is_negation'] == True)
    df_clean = df[~mask_drop]
    
    # 2. Identify missing negations
    # Find fact_ids that already have a negation
    has_negation = df_clean[df_clean['is_negation'] == True]['fact_id'].unique()
    
    # Filter for candidates:
    # - Not in has_negation (so we need to generate one)
    # - type != 'overruled' (we don't generate negations for overruled claims)
    # - is_negation == False (we look at the positive sample to generate the negative)
    candidates = df_clean[
        (~df_clean['fact_id'].isin(has_negation)) & 
        (df_clean['type'] != 'overruled') & 
        (df_clean['is_negation'] == False)
    ]
    
    print(f"Number of claims requiring negation generation: {len(candidates)}")
else:
    print(f"File not found: {file_path}")

Number of claims requiring negation generation: 0